setup.py
For the build process, Windows SDK registry search paths were added for v7.0A and v7.1A.
=> Windows SDK registry search paths

src/runtime/classobject.cs, src/runtime/constructorbinder.cs, src/tests/test_class.py
I updated the ConstructorBinder to support the creation of struct instances by calling the struct's default constructor which allows users to create instances of structs with no explicit constructors defined.
=> Struct default constructor

setup.py
Needed for non-windows builds.
=> Include Python.Runtime.dll.config in sdist.

src/runtime/classobject.cs, src/runtime/indexer.cs, src/runtime/methodbinder.cs, src/testing/indexertest.cs, src/testing/methodtest.cs, src/tests/test_indexer.py, src/tests/test_method.py
In my local code I ran into a issue with default arguments. The code in the methodbinder.bind check if the arguments given is less than the arguments needed. If it is true check if there are any default arguments if so pull the default values.
The one exception is the indexer where setter is mapped to the arguments are passed along with the value. An example  T[k1, k2] = v would be passed down as a tuple like (k1,k2,v). I had to check for the default arguments in the mp_ass_subscript method before calling the SetItem. 
I've included simple unit tests that tests the default argument for method calls and indexers.
=> Method Default Arguments

appveyor.yml
Drop tests for Python 2.6 and 3.2 as pip no longer supports those versions.
Add tests for Python 3.3.
=> Fix appveyor config.

src/runtime/classbase.cs, src/runtime/generictype.cs, src/runtime/genericutil.cs
This fixes issues #157 and #128 by allowing the use of the type
subscript operator on all types instead of just generic types,
preventing the shadowing of generic types by a non-generic one like
System.Action or System.EventHandler.
=> Move the type subscript implementation into ClassBase.

src/runtime/converter.cs, src/runtime/importhook.cs, src/runtime/interop.cs, src/runtime/metatype.cs, src/runtime/methodwrapper.cs, src/runtime/typemanager.cs, src/tests/test_exceptions.py
This implements the `__instancecheck__` method on the CLR metaclass which results in `isinstance` working for interfaces. I'm not completely sure whether everything still works and this is missing the `__subclasscheck__` to make `issubclass` work accordingly.
Also, I'd like to simplify the method def generation in `MethodWrapper` and this particular implementation as a prerequisite to implementing `__enter__` and `__exit__` for `IDisposable` objects.
=> [WIP] Implement __instancecheck__.

demo/wordpad.py
This fixes the problem with the open and save dialogs freezing the
application.
=> Start the wordpad demo in an STA thread.

demo/wordpad.py
FileStream.Read returns (bytes read, buffer), not just bytes read as the
buffer is passed by reference. This is a bit unintuative, but checking the
position is clear and less error prone.
=> Use stream position instead of counting read bytes.

demo/wordpad.py, src/tests/test_method.py
Open CSharp Interactive:
```csharp
var s = string.Join("", Enumerable.Repeat("a", 1024)) + "\r\nb";
File.WriteAllBytes(@"C:\Test\file.txt", System.Text.Encoding.UTF8.GetBytes(s));
```
Open wordpad demo
```
python demo/wordpad.py
```
Now open `C:\Test\file.txt`.
Expected:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa …
```
=> Fix demo stream reading

setup.py
While _find_msbuild_tool searches in the registry to find the given
build tool, it doesn't check if it's already in PATH.
If one uses a developer command prompt to build, all necessary tools are
in PATH.
Fixes #207 for me
=> Use msbuild tools from PATH if available

src/runtime/assemblymanager.cs
Not sure why PythonNet was getting this exception (only on production server not dev machine).  Running my module with `python -m mymodule` would work fine.  Anyways, I debugged a bit and the attached change fixed my issue.
Please note this is a quick hack, just to keep my project going and it worked.  I have no idea of the underlying cause and do not want to investigate but if you think my change is not risky you may want to merge as it does fix this issue (or at least hides the issue).
A quick [Google](https://www.google.com.au/search?num=100&q="Name+must+not+be+empty%21"+PythonNet) shows that I'm not the first to get this exception.
Exception Details:
```
System.ArgumentException: Name must not be empty!
at Python.Runtime.ModuleObject..ctor(String name) in …
```
=> Fix crash "Name must not be empty!"

setup.py
In Linux with Mono, NuGet leaves error message:
Unable to find version '1.2.6' of package 'UnmanagedExports'.
It can be simply solved by updating nuget.exe itself, but that's not obvious through error message, so I modified setup.py.
=> quick fix for old nuget can't find packages

src/runtime/clrobject.cs, src/runtime/converter.cs, src/runtime/exceptions.cs, src/runtime/interop.cs, src/runtime/managedtype.cs, src/runtime/moduleobject.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs, src/tests/test_exceptions.py
Fixes #284.
This PR contains 3 componenents:
1. Remove all of the Py<2.5 workarounds that wrap exceptions in old-style class instances
2. Fix #284 by moving the exception args into the corresponding slot in the `BaseException` object instead of faking the functionality by overloading `__getattr__`
3. Remove the `__getattr__` overload altogether since the only functionality it provides (lookup of `.message`) is deprecated in Python >= 2.6
=> Fix exception pickling

src/runtime/assemblymanager.cs, src/testing/Python.Test.csproj, src/testing/moduletest.cs, src/tests/test_module.py
We observed a spurious crash when a spawned .NET thread loaded some additional assemblies triggered the AppDomain.AssemblyLoad event handler. This modified the namespaces Dictionary and led to an exception
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>    at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
>    at Python.Runtime.AssemblyManager.GetNames(String nsname) in C:\git\pythonnet\src\runtime\assemblymanager.cs:line 442
when we called import clr again from the Python thread. I was able to write a test which reproduces this (most of the time).
As a fix I propose to make namespaces a ConcurrentDictionary. The same …
=> Assemblymanager thread safety

.gitignore, appveyor.yml, ci/install.ps1, ci/run_with_env.cmd, conda.recipe/bld.bat, conda.recipe/meta.yaml
closes #210 
- builds a ``clr`` conda package
- builds for 2.7/3.5 on windows (will simply fail on other platforms), should be easy to extend though
- fixes the non-standard dev tag (-dev is not valid, should be .dev, but no big deal)
- release tags *should* work, but not actually tests (e.g. should generate ``clr-v2.2.0-py35``
- the actual installation should *really* be into a ``site-packages\clr\`` sub-dir in the target, but this just mimics how the wheels work.
=> conda.recipe

src/runtime/metatype.cs, src/runtime/runtime.cs, src/tests/test_class.py
- When modifying attributes on a class, PyType_Modified has to be called
- The result of a lookup may be non-NULL without being a descriptor (e.g. if we
set it manually using `Class.attribute = 1`)
Fixes issue #292
=> Fix attribute setting

src/runtime/classbase.cs, src/runtime/runtime.cs, src/tests/test_class.py
I've rebased and squashed @ArvidJB's changes and removed the obsolete `tp_compare` implementation such that we get comparison operators for both Python 2 and 3.
I suggest we merge this one instead and close #291.
@tonyroberts @denfromufa @vmuriart @matthid Please review.
=> Comparison operators as implemented by ArvidJB in #291

conda.recipe/meta.yaml
This matches the project and (more importantly) pypi name.
=> Rename the conda package to pythonnet.

AUTHORS.md, CONTRIBUTING.md, LICENSE, setup.py, src/console/assemblyinfo.cs, src/runtime/assemblyinfo.cs
=> MIT License

src/runtime/assemblyinfo.cs, src/runtime/runtime.cs
-   Refactors the [UCS4/UC2 PY2/PY3](https://github.com/pythonnet/pythonnet/blob/c95b8f3fdcda1957b4d6e499a7dd5d3f0e1b51c8/src/runtime/runtime.cs#L1609-L1853) logic and clarifies when each section is applicable.
-   Completed clean-up of unneeded PYTHON2x PYTHON3x definitions 
Python37 can be added to travis after merging both #329 and #335.
This would allow travis to test `geninterop` and we can monitor python37 if it introduces any breaking changes.
=> String directives cleanup on Runtime

.travis.yml, README.md, appveyor.yml, ci/appveyor_build_recipe.ps1, ci/appveyor_run_tests.ps1, conda.recipe/README.md, src/embed_tests/packages.config, tox.ini
- Add coverage (cs code limited to windows, no mature coverage tools for mono)
- Speed up AppVeyor by 50%, conda recipes built only when `pull_request`
- Speeds up Travis ~30% by using containers
- Simplifies and unfreezes mono setup
#237 
#334
Redid the previous pull request. (#335)
Sample [coverage](https://codecov.io/gh/vmuriart/pythonnet/tree/1cfe592ae8806847bfb9c2581cef5ebac771c7c3) report.
=> Coverage & CI Setup Improvement

src/embed_tests/InitializeTest.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs
Implements an overload of `Initialize` and a `Py.SetArgv` function that allow the user to issue a `PySys_SetArgvEx` call. By default, this call is done on `Initialize` with a list that contains a single empty string (`['']`), using the arguments supplied to the .NET process if available.
#299.
Based on the `fix-shutdown` branch as otherwise I'm not able to run the unit-tests reliably..
=> Add pysetargv

appveyor.yml, ci/appveyor_run_tests.ps1, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/packages.config
Enables embedded unit tests on AppVeyor
Shows failing tests on python3 during finalization but can't reproduce locally. It isn't consistent on AppVeyor either.
Downgrades nunit to 2.6.4. It can deal better with exceptions that occur during finalize, unit3 just freezes and holds the ci worker until AppVeyor times it out.
=> Enable Embedded Unit Tests

src/runtime/converter.cs, src/runtime/exceptions.cs, src/runtime/importhook.cs, src/runtime/runtime.cs
Proof of concept to separate build directives from runtime to make it Python version agnostic.
Replaces some build directives with runtime `if` statements. 
Ideally continuing down this path would allow us to move the build directives to a few files and allow pythonnet to be mostly python version agnostic. 
Maybe lays the ground for #165.
Based on some of the work from @dmitriyse.
=> [POC] Replace build directives with runtime checks

Python.Runtime.dll.config, src/clrmodule/clrmodule.csproj, src/clrmodule/packages.config, src/console/Console.csproj, src/console/app.config, src/embed_tests/Python.EmbeddingTest.csproj, src/runtime/Python.Runtime.csproj, src/testing/Python.Test.csproj
-  Greatly simplifies the project properties but refactoring all the common properties to the general scope.
-  Separates the `Configuration`/`Platform` properties to cut the combinations in half
-  Centralizes location of Framework version 
-  Strong name signs packages (#214)
-  Generates xml-docs during build
Closes #214
=> Clean-up project properties

ci/appveyor_run_tests.ps1, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/pyimport.cs, src/embed_tests/pyinitialize.cs, src/embed_tests/pyiter.cs, src/embed_tests/pylong.cs, src/embed_tests/pyobject.cs, src/embed_tests/pythonexception.cs, src/embed_tests/pytuple.cs
- Simplifies multiple tests to use a simpler setup.
- Adds tests to `PyTuple` based on where coverage wasn't being exercised.
- Renames `InitializeTest` to `pyinitialize` since thats the naming style all other tests use.
`n/a`
Increases coverage
=> Simplify Embedded tests & Add new tests

.travis.yml, appveyor.yml, ci/appveyor_run_tests.ps1, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/packages.config
Since the embedded unit tests have been patched we can re-upgrade to `NUnit3` from @filmor .
`N/A`
On `v.2.x` of NUnit I'm noticing that the tests finish and hang for ~40 seconds before releasing control. on `v3.x` it gives some warnings but I'm not sure if thats related. 
Personally I'm indifferent to prefer `v2.x` since it released control and occasionally print the traceback that was key to figuring the old problem out. But since that looks to be solved, I don't have a strong argument.
=> Upgrade NUnit to 3.6

AUTHORS.md, CHANGELOG.md, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/dynamic.cs, src/runtime/pyobject.cs
This implement the function of passing an arbitrary .NET object as attribute of PyObject by dynamic type. 
Four modifications are located at file pyobject.cs, the methods for dynamic type TryGetMember and TrySetMember were modified, a new method GetAttrDynamic was added for TryGetMember, and a new method SetAttrDynamic was added for TrySetMember.
Unit tests were given in a new file "src/embed_tests/dynamic.cs".
An Example was given in the discussion of issue [#370](https://github.com/pythonnet/pythonnet/issues/370) , the Solution 4.
/***********Information below is outdated and can be removed*************/
However this doesn't fix the issue [why sys.stdout returned null #370](https://github.com/pythonnet/pythonnet/issues/370)
...
...
I don't know where to put the test, so I put it here. …
=> Passing an arbitrary .NET object as the value of an attribute of PyObject

.travis.yml, appveyor.yml, src/testing/Python.Test.csproj, src/tests/conftest.py
Ensures that `Python.Test` is output to same location on both Linux and Windows
as part of build.
Remove the need to manually copy or locate `Python.Test.dll` for local testing. 
No longer need that line in the [wiki](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux#tests-passing).
Simplifies CI setup.
`.gitkeep` to ensure the fixture folder is part of version control (and no need to recreate)
Can be removed if any file is added to it later on.
=> Standardize Python.Test fixture location

src/embed_tests/pyinitialize.cs
Add a **MINIMAL** unit test function for Overflow Exception and across AppDomains Exception reproduction.
The MINIMAL steps to reproduce these exceptions can be concluded into,
1. During the first time PythonEngine Initialize and Shutdown, import **ANY** class or struct from .NET.
2. After the second time PythonEngine Initialize, import **THE SAME** class/struct from .NET.
3. Create an instance of **THE** .NET class/struct in Python, then the System.OverflowException Exception will be raised here. If replacing int with Int64, OverflowException will be replaced with AppDomain exception.
Usage:
Call this test function in the C# code with,
```
new Python.EmbeddingTest.PyInitializeTest().ReInitialize();
```
=> Minimal unit test for Overflow Exception and across AppDomains Exception reproduction

src/runtime/methodbinder.cs, src/testing/methodtest.cs, src/tests/test_method.py
Fixes Method object overloading without breaking changes introduced by #131 and #151.
I added the tests/examples from #131 to the [tests](https://github.com/pythonnet/pythonnet/blob/6afc9e684856fca988c6d5260ee2d6de3735b7cf/src/tests/test_method.py#L748-L771) to ensure that the behavior didn't get reverted.
Closes #203 
This patch fixes the issue from #203, but `MethodBinder.Bind` needs rewriting since its basically been patched over and over again to fix edge cases. I didn't want to do it as part of this `pull_request` since it would affect more than just fixing #203.
=> Method overload object type

.travis.yml, src/embed_tests/dynamic.cs, src/embed_tests/pyinitialize.cs, src/embed_tests/pytuple.cs
Enables embedded tests on Travis
Closes #224 
Enabling the test exposed a few bugs in PY2/PY3 pythonnet on Linux. I've opened tickets for a couple of them. 
I've added the error messages to the tests and a [conditional ignore](https://www.amido.com/code/conditional-ignore-nunit-and-the-ability-to-conditionally-ignore-a-test/)  testing. As the issues get fixed, the conditional on the tests can be removed.
=> Enable Travis Embedded Tests

src/embed_tests/pytuple.cs, src/runtime/pythonexception.cs
Re-enable most `PyTuple` tests on PY27/Travis.
Prevent GC trying to deref values after python has been closed.
`Fails on Travis/PY27: Fatal Python error: auto-releasing thread-state, but no thread-state for this thread`
Seen mostly on PY27/Travis on PyTuple tests during GC of tests.
```
Fatal Python error: auto-releasing thread-state, but no thread-state for this thread
Stacktrace:
at (wrapper managed-to-native) Python.Runtime.Runtime.PyGILState_Release (intptr)
at Python.Runtime.PythonEngine.ReleaseLock (intptr)
at Python.Runtime.PythonException.Dispose ()
at Python.Runtime.PythonException.Finalize ()
at (wrapper runtime-invoke) object.runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr)
```
Similar fix to #365.
Since `PythonException` doesn't inherit from `PyObject`, need …
=> Fix PythonException GC -  no thread-state for this thread

src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/pyrunstring.cs, src/runtime/pythonengine.cs
"eval" and "exec" are two of the most frequently used methods when interacting with Python. However, I found there is not "eval" provided currently, this statement var flag = (IntPtr)257; in PythonEngine.RunString method makes this method can only be used as "exec".
Two .NET functions equivalent to the Python “evel” and “exec” are implemented by wrapping the PyRun_String function just like the CPython does. PythonEngine.RunString method became internal.
All the modifications located in pythonengine.cs.  All the places using  PythonEngine.RunString are replaced with the new PythonEngine.Exec method.
Unit tests are given in the new file "src/embed_tests/pyrunstring.cs", They can also be used as examples. List one of them below.
Eval the python expression "sys.attr1 + a + 1" and obtain its …
=> Add PythonEngine Eval and Exec

src/runtime/pythonengine.cs, src/tests/test_sysargv.py
Closes #404.
Introduces a `setSysArgv` flag to all `Initialize` functions in `PythonEngine`, defaulting to `true` and set to `false` for `InitExt` such that `import clr` doesn't call `PySys_SetArgvEx`.
#404.
The test should already be in from another PR, from what I understood and since the change introducing this issue has not been released, yet, I don't think it need to go into the changelog.
=> Fix the issue of sys.argv being cleared on import clr.

setup.py
Following #392, an OSX native `ldd` equivalent command (`otool -L`)
No, still have to manually add the symbolic links (see again #392) for import to work.
```
(py36) vasilios@exumas: /usr/local/anaconda/envs/py36/lib
└─ $ ln -s /Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono mono
```
=> Added branching for ldd command in OSX

src/runtime/runtime.cs
Simplify calls to `dllImport` by removing arguments that are default, not-applicable, or redundant.
`n/a`
The clean-up exposes where CharSet is actually needed to marshal Strings. 
=> Clean dllImport calls in Runtime

src/embed_tests/TestPythonEngineProperties.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs
Fixes setters for `PythonEngine.PythonHome` `PythonEngine.ProgramName` and `PythonEngine.PythonPath`. 
It extends #279/#186: 
- Fix the issue in Python 2/3 and 32/64bit
- Fix memory leak on multiple `setters`
Closes #179
Closes #279 (replaces)
Closes #186 (replaces)
There's quite a bit of repeated code on this `pr`. I'll perform the clean-up after this `pr` is merged to avoid obscuring how this is being fixed. 
`PythonEngine.PythonPath`, is misleading since it doesn't directly map to `PYTHONPATH` and should be called `Path` instead. `py_set_path` doesn't exist on `PY27` but it was erroneously defined at some point. 
Needs to be removed, but its outside the scope of this `PR`.  …
=> Fix set pythonhome

README.md, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/TestExample.cs, src/runtime/converter.cs
Generic Lists were falling through and being classified as `typecode.Object`
To solve this, adding a specific processing branch for `Generic Lists` only
to avoid breaking the changes from 471673a1fa4691b3becb4d9fee6941308535bb04
Closes #249
`n/a`
=> Fix numpy array and README example

setup.py, src/embed_tests/Python.EmbeddingTest.csproj, src/runtime/Python.Runtime.csproj, src/testing/Python.Test.csproj
My attempt to fix Travis CI after the upgrade to mono 5.0. Should fix #464 and let #461 be merged.
I have checked setup.py on osx with mono 5.0, the problem is the escaping of constants to the /p:DefineConstants arguments to msbuild. After trying several things, I'm escaping with %3B (semicolon), should be fine in windows as well. 
I don't have a linux box to test now or a travis setup to verify further, so I'm pushing the PR and will see the results of pythonnet travis. We can take it from there.
=> Fixing Travis CI for mono 5.0

AUTHORS.md, CHANGELOG.md, src/runtime/typemanager.cs, src/tests/test_subclass.py
Fix crash of python interpreter 3.5 64-bit in garbage collector
If Python class is derived from .NET class and __namespace__ or __assembly__ attributes are set then python interpreter crashes in garbage collector. Provoke garbage collector run by:
```
import gc
gc.collect()
```
#481 and may be others
=> Fix missing Incref for Namespace and Assembly

AUTHORS.md, CHANGELOG.md, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/TestConverter.cs, src/runtime/converter.cs, src/tests/test_conversion.py
As there was a range check both for `float` and `double` values, which are less or greater than its `MinValue` and `MaxValue` accordingly,
several values like `float.NegativeInfinity`, `float.PositiveInfinity` and the same 'double' values cannot be converted from Python to .NET values.
Due to Python C API documentation, method `PyFloat_AsDouble` can return `-1.0` upon failure. So it requires error check. This rule forces to check for error and throw exception in case of error.
Resolves: #486
=> Fix conversion of 'float' and 'double' values

src/runtime/pyscope.cs
`PyObject_TYPE` does not `Incref` the type object returned, in contrast to `PyObject_Type`, which was used here before.
=> Fix check in PyScope so that we don't leak a reference.

CHANGELOG.md, src/runtime/classderived.cs, src/runtime/metatype.cs, src/runtime/runtime.cs, src/tests/test_subclass.py
Remove the extraneous call to `__init__` from `ClassDerived.InvokeCtor`.
#495 
This is a different shot at fixing #495 . @filmor has one at #496 but it fails a couple of tests. This one might have some bugs wrt `XDecref` in `MetaType.tp_call` still.
=> Another shot at #495

src/runtime/Python.Runtime.csproj, src/runtime/Util.cs, src/runtime/clrobject.cs, src/runtime/managedtype.cs, src/runtime/metatype.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
On Windows 64bit systems, a C `long` is a 32 bit integer while the rest
of the world has agreed on making `sizeof(long) == sizeof(void*)`.
New attempt on #376
@vmuriart Do you have a test-case for PR #376?
=> Handle C long size on Windows.

requirements.txt
Currently, a github tag is used for the codecov requirement in requirements.txt. This PR replaces that with the regular PyPI version.
No.
...
...
=> Use PyPI published version of codecov

appveyor.yml
The recent PR that updated codecov to 2.0.9 broke uploading of C# coverage. This PR is intended to restore that.
No.
=> Explicitly specify files to upload to codecov

src/runtime/nativecall.cs
Workaround for the DotNet Core 2.0 marshaling bug.
Problem described here https://github.com/pythonnet/pythonnet/issues/96#issuecomment-329542908
...
...
...
=> Marshalling fix for 3-IntPtr args cdecl calls.

src/embed_tests/pyrunstring.cs, src/runtime/pythonengine.cs
This PR makes the RunString method acts just like the exec/eval method in CPython.  
In CPython, the default value of parameter 'locals' of  exec/eval method is obtained by calling the method locals() when its given value is None.  So only when the exec/eval method is called in a function, the default value of parameter 'locals' is different from the value of  'globals'. 
Since in pythonnet the Eval/Exce method can only be called from the global/module scope, it meaningful to directly set the value of locals to the value of globals when it is null.
...
[#591](https://github.com/pythonnet/pythonnet/issues/591)
...
No.
...
-   [ ] If an enhancement PR, please create docs and at …
=> fixed bug of Exec method #591

CHANGELOG.md, src/runtime/managedtype.cs
fix for "handle is not initalized" crash on `clr.GetClrType(System.__class__)`
https://github.com/pythonnet/pythonnet/issues/606
=> fix for "handle is not inialized" crash on `clr.GetClrType(System.__class__)`

src/embed_tests/dynamic.cs, src/runtime/pyobject.cs
enumerable python object cannot be directly enumerated through PyObject.
```C#
dynamic pyCollectionObj = new PyObject(collectionObjIntPtr);
foreach (dynamic item in pyCollectionObj)
{
// This code currently does not works.
}
...
No
...
Tests are failed due to NUnit Assert.Equals behavior. When object is IEnumerable Assert.Equals also compares all items.
...
=> PyObject was made IEnumerable

src/runtime/Python.Runtime.csproj
This change removes the file interop33.cs from the Visual Studio project. In a previous commit, this file was deleted but was not removed from the project file.
This fixes #688.
=> Removing deleted file from project

AUTHORS.md, CHANGELOG.md, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/TestPyObject.cs, src/runtime/pyobject.cs
This change implements GetDynamicMemberNames() for PyObject. This allows dynamic object members to be visible in the Visual Studio debugger.
#443
=> Implementing GetDynamicMemberNames() for PyObject

AUTHORS.md, CHANGELOG.md, src/runtime/methodbinder.cs
When a method does not find a match for given arguments, the thrown runtime error message does not informs us which method call failed.
No.
No.
=> Adds method name to "no method matches" error

appveyor.yml, setup.py
Continuous integration on pythonnet/master is broken at the moment. This patch gets to green-light on master.
(1) Travis now has msbuild 15 available, which breaks the no-arg build since it's using the pythonnet.sln which is msbuild 14. Fixed by forcing the use of msbuild 14.
(2) Appveyor on py34 is failing to build psutil. Newer python and py27 are using binary releases so the problem doesn't show up. I couldn't figure out how to fix it, so I made it an allowed failure.
=> Fix travis, work around appveyor build breaks

src/runtime/importhook.cs, src/runtime/moduleobject.cs, src/tests/importtest.py, src/tests/test_import.py
If module has been imported for once, `from module import *` can only get the attributes which in `__dict__`.
This PR add a check and load for every time when `import *` if it's a CLR module.
...
Perhaps we can ignore changes after `import *`, and just enough for callling `ModuleObject.LoadNames` once.
=> Fix "from import *" failed after a normal import

AUTHORS.md, CHANGELOG.md, src/embed_tests/Python.EmbeddingTest.15.csproj, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/TestDomainReload.cs, src/embed_tests/TestRuntime.cs, src/embed_tests/TestTypeManager.cs, src/embed_tests/dynamic.cs, src/runtime/classbase.cs, src/runtime/extensiontype.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
The Unity editor unloads the C# domain and creates a new domain every time it recompiles C# sources.
This caused two crashes.
1. After a domain unload, python is now pointing to a bunch of objects whose C# side is now garbage. **Solution**: Shutdown() the engine on domain reload, which calls Py_Finalize.
2. After a domain unload, Py_Finalize, and a new Py_Intialize, python still keeps pointers in gc for any python objects that were leaked. And pythonnet leaks. This means that python's gc will be calling tp_traverse, tp_clear, and tp_is_gc on types that are implemented in C#. This crashes because the implementation was freed. **Solution**: implement those calls in code that is *not* released on domain unload. Side effect: we leak a page on every domain unload. I suspect but didn't test …
=> Enable pythonnet to survive in the Unity3d editor environment.

setup.py
msbuild fix for vs2017 - do not specify msbuild version
https://github.com/pythonnet/pythonnet/issues/720#issuecomment-434976056
https://github.com/pythonnet/pythonnet/issues/720#issuecomment-434976056
ignore msbuild version, because errors out in vs 2017
=> Update setup.py for msbuild requirements

CHANGELOG.md, src/embed_tests/pyinitialize.cs, src/runtime/pythonengine.cs
New feature: allow user code to clean up before python.net shuts down. We use it in a client-server architecture, with python.net on the server and a pyside UI on the client. This callback lets us clean up gracefully.
I decided to also use the feature in order to help PythonEngine itself set up / shut down correctly, because dog food is tasty. And there's a unit test.
Not on pythonnet.
I'm not clear on the division of labour between PythonEngine and Runtime. User code tells the PythonEngine to initialize, not the runtime, so that seemed the place to put the shutdown handler.
But it could just as well be in the runtime, and the runtime also needs the same pattern of building up / tearing down in the opposite order. User code could still think it's PythonEngine handling it (just make …
=> Allow user code to register for a callback on shutdown.

src/runtime/Python.Runtime.15.csproj
On case-insensitive UNIX-like systems (e.g. macOS), copying `System.XML.dll` to `System.Xml.dll` will cause the build to fail. 
The fix (or hack) is to check for existence of `System.Xml.dll` before running `cp`.
Fixes #768 
=> Fix: do not cp System.XML on case-insensitive fs

CHANGELOG.md, pythonnet.sln, src/embed_tests/dynamic.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs
Minimal version of #724, allows the user to select whether an embedded Python should configure signal handlers or not, defaulting to "false" (which is different from what we had before as a straight call to `Py_Initialize`  will configure signal handlers).
Fixes #449.
We should follow up on #724 to get a unit test working for this, but this can wait until after 2.4.0.
=> Minimal Py_IntializeEx change

src/runtime/pyobject.cs, src/runtime/runtime.cs
Fixes #802.
TrueDivide is supported in both Python 2 and 3 while Divide exists only in Python 2. This does mean that a simple division of numbers will behave differently in C# vs Python for Python 2, but it will at least
behave the same way in C# independent of the Python version being used.
=> Switch to using TrueDivide instead of Divide everywhere

.travis.yml, appveyor.yml, src/embed_tests/TestTypeManager.cs
- Drop Python 3.4 from CI (in accordance with silence on #817)
- Disable writing to the protected page from Mono as it results in a SIGSEGV on 5.18 (it threw an exception on 5.16).
=> Fix unit tests

AUTHORS.md, CHANGELOG.md, setup.py
When I try to run `setup.py install`, the installation failed with the following error:
```
RuntimeError: mt.exe could not be found
```
Because setup.py is searching for specific versions of the Windows 10 sdk.
This patch changes that behaviour to use the installed Windows 10 sdk instead of relying on specific versions.
No.
I kept the existing hard-coded sdk version to ensure that this is a non-breaking change.
The objective of this patch is make installation easier.
=> List installed Win10 SDK's when looking for windows sdk tool

src/runtime/moduleobject.cs
Reverts pythonnet/pythonnet#655, "contains #841" and fixes #732 .
If anyone (in particular @icetiger1974 who contributed this patch) wants to have another go on it, please ensure that only the actually thrown exception message is modified instead of introducing a whole new error condition.
=> Revert zone check for assembly loading

src/embed_tests/TestFinalizer.cs, src/runtime/finalizer.cs
- The callback set by `Runtime.Py_AddPendingCall()` was not being
triggered in some cases in a multithreaded environment. Replacing it
with a `Task`
Changes cherry-picked from https://github.com/QuantConnect/pythonnet/pull/29
After 
Before
=> Make finalizer use a task

src/embed_tests/TestRuntime.cs, src/runtime/Python.Runtime.csproj, src/runtime/platform/LibraryLoader.cs, src/runtime/platform/Types.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
Moves the library loader to three separate classes that contain implementations for Darwin, Linux and Windows s.t. they can be initialized at runtime.
Nope, but it brings us further towards a single build.
=> Get the correct library loading functions at runtime

CHANGELOG.md, src/embed_tests/TestCallbacks.cs, src/runtime/methodbinder.cs
This change adds more information to "No method matches given arguments" message. In particular, it collects types of arguments passed by Python. For example:
> No method matches given arguments for Add: (<class 'list'>, <class 'tuple'>)
=> Improve "No method matches given arguments" message with more details

CHANGELOG.md, src/runtime/runtime.cs
A small number of existing imports are deprecated in Python3. 
This removes them or compiles them out.
Fixes #924 
...
N/A
-   [N/A] Make sure to include one or more tests for your change
-   [N/A] If an enhancement PR, please create docs and at best an example
=> Removes imports deprecated in Python3

AUTHORS.md, CHANGELOG.md, src/runtime/runtime.cs
Currently the PyModuleType is deduced from the ``__builtin__`` module. However, this fails when some third party package messes with this module (Nuitka). In this PR the PyModuleType is deduced directly from the Python shared library instead, which should be a safer approach to achieve the same.
#904 
...
=> Fix so that Runtime.PyModuleType is retrieved via Python.dll (#904)

AUTHORS.md, CHANGELOG.md, src/runtime/converter.cs, src/tests/test_array.py
Python 3 has much more liberal use of iterators, e.g. getting keys or values from a dictionary. This adds functionality to convert python object which support the iterator protocol to arrays in C#.
No
N/A
=> Adds support to convert iterators to arrays

CHANGELOG.md, src/runtime/nativecall.cs
Fixes an issue where pythonnet attempts to cast one managed delegate to another. This is explicitly forbidden in the documentation: [see here](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getdelegateforfunctionpointer?view=netstandard-2.0#System_Runtime_InteropServices_Marshal_GetDelegateForFunctionPointer__1_System_IntPtr_). In particular:
> You cannot use this method to create a delegate from a function pointer to another managed delegate
I have also removed the usage of the obselete function GetDelegateForFunctionPointer(IntPtr, Type) and replaced it with GetDelegateForFunctionPointer<TDelegate><IntPtr).
No
It seems like this issue got partially fixed in PR #550 and was mentioned in issue #96. See also this related …
=> Remove delegate casting

README.rst
Added resources section with mailing list and chat
Puts discussion resources in the readme. The gitter link is in a badge at the top, but is easy to miss. The mailing list is not referenced at all (as far as I can tell).
=> Update readme with resources

CHANGELOG.md, src/runtime/converter.cs, src/runtime/runtime.cs
As described in Issue #950, the size of python's longs can vary depending on platform. This changes allows pythonnet to determine at runtime the architecture of the python interpreter and select the correct size of long/int for the affected methods.
#950 
No
=> Detect py arch

AUTHORS.md, CHANGELOG.md, src/runtime/pythonengine.cs, src/runtime/runtime.cs
I'm using pythonnet to embed python 3.6 in a C# WPF application. I'm effectively booting up a venv with pythonnet and I noticed the user site folder kept getting included in `sys.path`.
There is a command line argument to disable this, (-S, more info here: https://docs.python.org/3/using/cmdline.html#id3) but as pythonnet loads python directly, this won't work.
There is a way to access this flag with the C API, info here: https://docs.python.org/3/c-api/init.html#c.Py_NoSiteFlag
This is a global variable that is exported, defined here: https://github.com/python/cpython/blob/3.6/Include/pydebug.h
My particular use case is for python 3.6, but it appears this flag is present in 2.7 and all currently supported 3.x versions.
Here is an example on how I am using this addition:
``` …
```
=> Add function to set Py_NoSiteFlag global variable to 1

src/runtime/importhook.cs
When C# shuts down we should restore Python to its original state.
This is adapted from the large patch that amos put in PR #958. It restores the import hook.
Not yet.
I would have used the ShutdownHandler but that's only in the PythonEngine, whereas `__import__` is in the Runtime. Maybe we should move the ShutdownHandler mechanism to the runtime?
Can't really test this at the moment. After Py_Finalize (in Shutdown), we can't check the state of the `__import__` function until we call Py_Initialize. But Py_Initialize will create a new `__import__`, so we can't see whether our code ran. This change only becomes relevant when we stop calling Py_Finalize in Shutdown.
-   [ ] If an …
=> Split from PR 958: restoring the __import__ after shutdown.

src/runtime/pythonengine.cs, src/runtime/runtime.cs
Since the `Py_CompileString` is a macro in `3.8.0`, a compatibility should be add, assume the release user don't use `Py_LIMITED_API`, we can implement it internal.
Also correct the type of `start` from `IntPtr` to `int`, according the protoype is `PyObject* Py_CompileString(const char *str, const char *filename, int start)`
https://github.com/pythonnet/pythonnet/pull/988#issuecomment-554718263
...
=> Internal implement Py_CompileString for compat with CPython 3.8.0

CHANGELOG.md, src/embed_tests/TestPythonException.cs, src/runtime/pythonexception.cs
This implements the ability to format an exception using traceback.format_exception. This is very useful for when you are embedding Python into an application and want to show the Python exception similar to how it would be printed in the Python console.
None that I know of.
=> Allow formatting an exception with traceback.format_exception

src/embed_tests/TestGILState.cs, src/runtime/pythonengine.cs
According to [`IDisposable` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?redirectedfrom=MSDN&view=netframework-4.8#remarks), `Dispose` method must be safe to call multiple times.
=> GILState.Dispose is safe to be called multiple times

src/perf_tests/BaselineComparisonConfig.cs
BenchmarkDotNet tuned the number of runs up to keep the total perf tests run time high. This reduces the number of runs per test further, which allows BenchmarkDotNet to do more runs of a smaller test to collect more information for better statistical results.
=> Reduce perf iterations further to keep up with BenchmarkDotNet autotuning

AUTHORS.md, CHANGELOG.md, src/runtime/moduleobject.cs
…during internal GetAttribute
It converts any exception retured from GetAttribute into a Python exception
Yes, Issue #1047 
=> #1047 ModuleObject __getattribute__ doesn't treat exceptions ocurred during internal GetAttribute

src/runtime/pythonexception.cs, src/runtime/runtime.cs
This clears references to Python objects from `PythonException` when it is disposed to prevent accidental use in the future.
No
This might help to fix [this crash](https://travis-ci.org/pythonnet/pythonnet/jobs/653883143?utm_medium=notification&utm_source=github_status), which happens immediately after exception handling tests.
=> Ensure Python handles are inaccessible after PythonException is disposed

.travis.yml, ci/appveyor_run_tests.ps1, src/embed_tests/Python.EmbeddingTest.15.csproj, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/packages.config, src/perf_tests/Python.PerformanceTests.csproj
My investigation of memory dump from https://github.com/pythonnet/pythonnet/issues/1050#issuecomment-589927118 did not reveal anything, that could be clearly caused by our code. The only thread, that runs our C# code is the one making the memory dump, and it is properly marked as `IsBackground = true`, so NUnit should ignore it.
If we upgrade our test dependencies to their latest supported versions, NUnit team would help us debug test execution deadlock. Alternatively upgrade might just solve the issue.
P.S. No need to review until CI passes for this PR, as I am unsure which test library configurations CI will support yet.
=> Update test dependencies to the latest stable versions

src/runtime/Util.cs, src/runtime/pythonengine.cs
`PyObject`s constructed for `__exit__` method referenced existing Python objects without increasing refcount appropriately, which could lead to double-free.
Not sure, but this issue might have been one of the possible causes for #1050
=> Fixed reference counting for exception objects in Py.With

src/embed_tests/TestRuntime.cs
This is an ongoing work on [random test crashes on Python 2.7 on Mono](https://github.com/pythonnet/pythonnet/issues/1060)
I've added error checks to the test, whose start precedes crashing (`PyCheck_Iter_PyObject_IsIterable_ThreadingLock_Test`). This might replace segfault with a more meaningful error message.
Not yet, but it should help narrow down #1060
=> Fix for random Travis test crashes with Python 2.7 on Mono

src/runtime/BorrowedReference.cs, src/runtime/NewReference.cs, src/runtime/NonCopyableAttribute.cs, src/runtime/Python.Runtime.15.csproj, src/runtime/Python.Runtime.csproj, src/runtime/assemblymanager.cs, src/runtime/methodbinder.cs, src/runtime/pydict.cs, src/runtime/runtime.cs
With C# 7.3 `ref structs` and C# 8.0 `using` working on any method named `Dispose` it is possible to track new vs borrowed references at compile time.
This proposal introduces `BorrowedReference` and `NewReference` types, that are `ref`-only structs, meaning you can't put them into `PyObject` directly, so they can implement different `ToPyObject` methods, one doing `IncRef`, and the other one not (alternatively, we can have `PyObject` constructor overloads). Along with Roslyn-based [NonCopyableAnalyzer](https://github.com/ufcpp/NonCopyableAnalyzer) and [FxCop](https://github.com/dotnet/roslyn-analyzers) after https://github.com/dotnet/roslyn-analyzers/issues/3305 is fixed, this can ensure, that we do reference counting correctly at compile time.
We can gradually change return and …
=> Proposal: Safe pointers

src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/References.cs, src/runtime/NewReference.cs, src/runtime/Python.Runtime.csproj, src/runtime/ReferenceExtensions.cs, src/runtime/pydict.cs, src/runtime/pyscope.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs
this also changes a few members of `NewReference` type to make them work in `PyRun_String` scenario
This PR is motivated by an observation of a crash after `PyRunString.TestExec2`. It calls `PythonEngine.Exec`, which in case of exception fails to decref `PyRun_String` result.
I replace `PyRun_String` return type with `NewReference` and handle it accordingly.
In the process of making this change it was discovered, that members of `NewReference` should be moved to an extension class, because in regular instance members `this` is passed by mutable reference (e.g. analogous to `ref NewReference` in C# or `NewReference&` in C++),
which requires any method calling this member to have a mutable reference to `NewReference`:
```csharp
bool TakeReference(NewReference reference)
// can use `IsNull` …
```
=> Correctly dispose the result of PyRun_String

CHANGELOG.md, src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/TestInstanceWrapping.cs, src/runtime/converter.cs, src/tests/test_conversion.py, src/tests/test_indexer.py
Previously when a C# method with a parameter of type `object` was called from Python with some argument of a native Python type (e.g. instance of `dict` rather than instance of `System.Random`), that would be considered a parameter type mismatch, so overload resolution would fail, and the C# method would not be called.
After this change, when Python tries to pass a argument of some Python type to a C# parameter of type `object`, that overload would be considered good for resolution, and the argument will be wrapped into `PyObject` and passed to the `object` parameter.
For example:
```csharp
void CallMe(object anything) => Console.WriteLine(anything);
````
```python
CallMe(dict())
```
Before change: overload not found
After change: `anything` in `CallMe` is an instance of `PyObject`, …
=> Retry: Enable C# parameters of type `object` accept any argument, passed from Python

src/embed_tests/pyimport.cs, src/runtime/BorrowedReference.cs, src/runtime/pylist.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs
Just playing with the new *Reference types to see what patterns might arise.
This adds:
- `PyObject.Reference` internal property, that exposes the same pointer as `obj`, but in a way, that it is clear, that the reference is borrowed
- `PyObject(BorrowedReference)` constructor, that extracts the address from the reference and `IncRef`s it before storing in the instance
- a few of the `PyList_*` methods now explicitly take `BorrowedReference` instead of raw pointers
=> Explorarion of the new *Reference types: reimplemented some of the PyList members using BorrowedReference

CHANGELOG.md, pythonnet.15.sln, src/embed_tests/TestConverter.cs, src/runtime/NewReference.cs, src/runtime/clrobject.cs, src/runtime/converter.cs
`GetRawPythonProxy` creates a `PyObject` pointing to the specified CLR object without performing any conversions, which lets .NET code to pass CLR objects as-is, if it needs Python to have direct access to them.
This is necessary to allow codecs to create arbitrary proxy objects for .NET objects, bypassing default conversions or other registered codecs.
This is related to #514
Without `GetRawPythonProxy` it is impossible for a user to define custom codec for `List<T>`, that returns raw proxy to `List<T>`, as they have no other means to obtain one.
-   [x] Add yourself to …
=> object.GetRawPythonProxy() extension, that bypasses all conversions

src/embed_tests/TestPyScope.cs
This adds `Lock` class-based synchronization to `update` Python function
in `PyScopeTest.TestThread` as suggested by @amos402 .
#1067
=> Add Lock synchronization to PyScopeTest.TestThread

src/runtime/Codecs/TupleCodecs.cs
When `TupleCodec.TryDecode` is trying to decode a tuple from Python to .NET, and the element type in Python does not match one in .NET, `Converter.ToManaged` on that element will fail and leave PyErr set. That caused it to be picked up later by a random check for PyErr and raised as .NET exception in unexpected places.
This change clears PyErr in `TryDecode` if decoding of an element fails, thus allowing other codecs/overloads to be probed safely.
=> Fixed TupleCodec not clearing Python exception after unsuccessful decoding

src/embed_tests/TestGILState.cs
Subj. `TestGILState` was missing `PythonEngine.Initialize` setup action.
=> Python runtime must be initialized before trying to acquire GIL

src/embed_tests/References.cs, src/runtime/NewReference.cs
implemented as an implicit conversion
To be honest, I would prefer an explicit `NewReference.Borrow()` method due to "explicit is better than implicit" motto. The only problem with implicit conversion that I see is `new PyObject(newRef)` will call an extra incref implicitly as opposed to `newRef.MoveToPyObject()`, and will go unnoticed.
Another thing to consider is having a `null`-check in the conversion. E.g. should we throw `NullReferenceException` if `NewReference` is `null`?
Related to #1087
=> Allow borrowing from NewReference

src/runtime/runtime.cs
This solves 
> error CS0165: Use of unassigned local variable 'dllLocal'
when building with `PYTHON_WITHOUT_ENABLE_SHARED`
Yes, #977
This restores build on many platforms, however, I am not sure about behavior on platforms, where python executable is not linked to libpython. The change is otherwise harmless.
=> fix compile error when PYTHON_WITHOUT_ENABLE_SHARED is not set

src/embed_tests/CodecGroups.cs, src/embed_tests/Codecs.cs, src/embed_tests/Python.EmbeddingTest.csproj, src/runtime/Codecs/DecoderGroup.cs, src/runtime/Codecs/EncoderGroup.cs, src/runtime/Python.Runtime.csproj, src/runtime/converterextensions.cs
These classes would help to manage codec layers. For example, a library could register its own codecs, but also allow anyone to inject their codecs before library's own:
```csharp
public static EncoderGroup BeforeLibraryEncoders { get; }
= new EncoderGroup();
LibraryRegisterCodecs()
{
PyObjectConversions.RegisterEncoder(BeforeLibraryEncoders);
PyObjectConversions.RegisterEncoder(LibraryEncoder.Instance);
}
```
Then in a program using that library:
```csharp
Library.BeforeLibraryEncoders.Add(preencoder);
```
No
=> Codec groups: EncoderGroup and DecoderGroup

setup.py, src/monoclr/pynetclr.h, src/monoclr/pynetinit.c
It was only used for `gobject` type, which is simply a pointer.
=> Remove unnecessary glib-dev dependency

src/embed_tests/CodecGroups.cs, src/embed_tests/Codecs.cs, src/runtime/Codecs/RawProxyEncoder.cs, src/runtime/Python.Runtime.csproj, src/testing/conversiontest.cs, src/tests/test_conversion.py
Now Python host can force raw encoding for autoconverted .NET types.
This class allows Python to override some automatic conversions done by Python.NET, which was otherwise impossible.
To do that, Python code can define a class derived from `RawProxyEncoder`, and override `CanEncode` to return `True` for the desired types. Create an instance of this class, and register it with `Python.Runtime.PyObjectConversions.RegisterEncoder(instance)` (see new test for example)
Enables workaround for #514
-   [x] Updated the …
=> RawProxyEncoder

CHANGELOG.md, src/embed_tests/Codecs.cs, src/embed_tests/TestConverter.cs, src/runtime/Codecs/RawProxyEncoder.cs, src/runtime/clrobject.cs, src/runtime/converter.cs, src/runtime/pyobject.cs
Reverts most of https://github.com/pythonnet/pythonnet/pull/1078
Turned out there already was `PyObject.FromManagedObject`. It was not covered by tests however, so I changed former `GetRawPythonProxy` tests to test `FromManagedObject`
No
=> Removes new object.GetRawPythonProxy extension method

setup.py, src/monoclr/pynetclr.h, src/monoclr/pynetinit.c, tools/geninterop/geninterop.py
Links `monoclr` as a C++ library and thus includes `libstdc++` and whatever else `g++` adds. Additionally, it force-loads `libmono-2.0` on Linux with `RTLD_GLOBAL` to make sure the symbols are in place when `libmono-native.so` is being loaded. 
I hope this fixes #939. The second part fixes #1034 on my machine.
-   [x] Make sure to include one or more tests for your change: N/A
-   [x] If an enhancement PR, please create docs and at best an example: N/A
=> Link stdc++

CHANGELOG.md, src/embed_tests/TestFinalizer.cs, src/runtime/clrobject.cs, src/runtime/finalizer.cs, src/runtime/pyobject.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs
This is an attempt to make finalizer much simpler.
Instead of using .NET async tasks, `Py_AddPendingCall` or other synchronization mechanisms we simply move objects to be finalized into a `ConcurrentQueue`, which is periodically drained when a new `PyObject` is constructed.
At the very least this should be resolved, as the new finalization code never tries to acquire GIL on its own: #1093
`Finalizer` is not in the baseline (e.g. Python.Runtime 2.3.0), but the following test drops from 98ms/op to 93ms/op on my machine:
```csharp
const int testObjectCount = 100000;
using (Py.GIL())
{
for (int i = 0; i < testObjectCount; i++)
new PyList();
}
GC.Collect();
GC.WaitForPendingFinalizers();
Finalizer.Instance.Collect();
```
-   [x] Make sure to …
=> Simplified Finalizer: drain finalization queue when new objects are created.

CHANGELOG.md, setup.py, src/runtime/PyExportAttribute.cs, src/runtime/Python.Runtime.csproj, src/runtime/assemblymanager.cs, src/runtime/polyfill/ReflectionPolifills.cs, src/testing/Python.Test.csproj, src/testing/nonexportable.cs, src/tests/test_class.py
Introduced [`PyExportAttribute`](https://github.com/pythonnet/pythonnet/wiki/PyExport), that can be applied to individual types or the entire assembly, and controls visibility of these types/assemblies to Python. This is useful in case .NET type has a name conflict with Python type.
The attribute in checked in `ScanAssembly`.
=> Allow excluding public .NET types from being exposed to Python via [PyExport(false)]

src/runtime/constructorbinder.cs, src/runtime/methodbinder.cs
Similar to #900, but for constructors (reuses the same code moved around)
This adds more details to "No constructor matches given arguments" message.
> No constructor matches given arguments
> No constructor matches given arguments for IntPtr: (int, list)
Does not close any issue, but is related to: #811, #265, #1116
=> Improve "No constructor matches given arguments" message with more details

.travis.yml, CHANGELOG.md, appveyor.yml, src/embed_tests/TestRuntime.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
Adds Python 3.8 to the CI and fixes the remaining issue by assigning `__classcell__` the created class if it exists. This is required as for the case of subclassing a C# class in Python, we (currently) don't initialise the type via `type_new` (`== PyType_Type.tp_new`) but instead generate it manually. The added code is done at the end of `type_new` and is required from Python 3.8 onwards (see command below).
=> Python 3.8

AUTHORS.md, CHANGELOG.md, src/runtime/classbase.cs
Fix incorrect dereferencing wrapper object in tp_repr function, which causes the program to crash.
...
...
-   [x ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [x ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)
=> Increase ob's ref count in tp_repr to avoid accidental free

src/runtime/methodbinder.cs
`item` is a return value of [`PyTuple_GetItem`](https://docs.python.org/3.8/c-api/tuple.html#c.PyTuple_GetItem) which returns borrowed reference.
Hence it should not have been decref'ed
=> fixed crash due to a decref of a borrowed reference in params array handling

appveyor.yml
Fix Windows CI currently not running functionally, it only test the release package not the present branch sources.
...
...
=> Fix appveyor would only test the PyPI package

CHANGELOG.md, src/embed_tests/pyimport.cs, src/runtime/assemblymanager.cs, src/runtime/exceptions.cs, src/runtime/importhook.cs, src/runtime/methodbinder.cs, src/runtime/moduleobject.cs, src/runtime/pylist.cs, src/runtime/pysequence.cs, src/runtime/pytuple.cs, src/runtime/runtime.cs
1. When trying to implicitly load assemblies, and that fails **not** because an assembly is missing, but because loading failed for some reason, emit Python warning.
2. When trying to import a module in our import hook, if the module name is an assembly name, and CLR fails to load it, and Python also fails to find a module with the same name, add the exceptions we got from both during the attempt into `__cause__` attribute of the final `ImportError`.
BREAKING: `clr.AddReference` will now throw exceptions besides `FileNotFoundException`.
Additional: a few uses of `BorrowedReference`
This addresses https://github.com/pythonnet/pythonnet/issues/261
It is an alternative to https://github.com/pythonnet/pythonnet/pull/298
-   [x] Make sure to …
=> Provide more info about failuers to load CLR assemblies

src/runtime/runtime.cs
Deprecated Python2 API:
* PyInstance_New
* PyInstance_NewRaw
Mere macros on C side:
* PyObject_CheckBuffer
* PyObject_GC_New (refer to `_PyObject_GC_New`)
Check method:
https://gist.github.com/amos402/fb41571856bc77a2bada8056e429b312
...
...
=> Remove non-existent PInvoke functions

CHANGELOG.md, src/runtime/methodbinder.cs, src/testing/methodtest.cs, src/tests/test_method.py
A bug in `ArgsPrecedence` caused parameters of type `object[]` to have the highest precedence, which affected `params object[]` handling, and also preferred `params object[]` to `params string[]` when a `string` argument was given.
#1211
...
=> Bad params object[] precedence

AUTHORS.md, CHANGELOG.md, src/runtime/typemanager.cs, src/tests/test_class.py
=> Ensure only implementers of IEnumerable or IEnumerator are considered Iterable

CHANGELOG.md, src/runtime/constructorbinder.cs, src/runtime/methodbinder.cs, src/testing/methodtest.cs, src/tests/test_method.py
If there were two methods with the same name, but with different arity,
`Foo(a)` and `Foo(a,b)`, and the latter was called with a keyword
argument `some.Foo(0, b=1)`, `Foo(0)` would be called instead of
`Foo(0,1)`.
Fixes #1235.
-   [] If an enhancement PR, please create docs and at best an example
-   [] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
=> Select correct method to invoke when keyword arguments are used

CHANGELOG.md, src/runtime/arrayobject.cs, src/runtime/converter.cs, src/runtime/interfaceobject.cs, src/runtime/managedtype.cs, src/runtime/methodbinder.cs, src/runtime/typemanager.cs, src/testing/interfacetest.cs, src/testing/subclasstest.cs, src/tests/test_array.py, src/tests/test_generic.py, src/tests/test_interface.py, src/tests/test_method.py, src/tests/test_subclass.py
This allows callers to call all methods of an interface, regardless of
whether the method was implemented implicitly or explicitly. Before this
change, you had to make an explicit cast to the interface to be able to
call the explicitly implemented method. Consider the following code:
```C#
namespace Python.Test {
public interface ITestInterface
{
void Foo();
void Bar();
}
public class TestImpl : ITestInterface
{
public void Foo() { };
public void ITestInterface.Bar() { };
public void Baz() { };
public static ITestInterface GetInterface()
{
return new TestImpl();
}
}
}
```
And the following Python code, demonstrating the behavior before this
change:
```python
from Python.Test import TestImpl, ITestInterface
test = TestImpl.GetInterface()
test.Foo() # works
test.Bar() # AttributeError: …
```
=> Wrap returned objects in interface if method return type is interface

AUTHORS.md, CHANGELOG.md, src/runtime/classobject.cs, src/tests/test_class.py
As mentioned in #1180, non-delegate types should not be appear as callable. Removed the `ClassObject.tp_call` method which seemed to be unused. Also added a test case.
Closes #1180.
=> Non-delegate types should not be callable

CHANGELOG.md, src/runtime/classmanager.cs, src/testing/indexertest.cs, src/tests/test_indexer.py
If a class A had indexer, and class B derived from it, Python.NET would
not consider class B to have any indexer.
No
=> Make it possible to use inherited indexers

src/runtime/runtime.cs
This fixes a compile error which must be a merge bug from the soft-reload branch landing.
=> Fixed dllLocal not being initialized.

src/runtime/classbase.cs, src/runtime/iterator.cs, src/tests/test_interface.py
Ensures that objects returned from an iterator are wrapped in an interface object if the iterator is for an interface type.
No
=> Return interface objects when iterating over interface collections

src/runtime/Python.Runtime.15.csproj
This enables [Source Link](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) and symbol package generation during build.
Source Link automatically pulls library (e.g. Python.NET) source code from GitHub when debugging.
=> Enable Source Link and symbol package generation during build

src/runtime/Python.Runtime.15.csproj, src/runtime/polyfill/ReflectionPolifills.cs
The `TypeBuilder.CreateType()` polyfill was incorrectly returning `typeof(TypeBuilder)` instead of the new type created using `TypeBuilder`.
https://github.com/pythonnet/pythonnet/issues/1228
=> Fixed polyfill for TypeBuilder.CreateType

src/console/Console.csproj, src/embed_tests/Python.EmbeddingTest.csproj, src/runtime/Python.Runtime.csproj, src/testing/Python.Test.csproj
"dotnet msbuild pythonnet.sln" fails in WSL2 because .targets files are wrongly cased, and Linux is case sensitive.
The command still fails, but at least for different error :).
=> fix wrongly cased Microsoft.CSHARP.Targets

src/embed_tests/TestDomainReload.cs, src/runtime/Python.Runtime.15.csproj, src/runtime/Python.Runtime.csproj, src/runtime/classbase.cs, src/runtime/classmanager.cs, src/runtime/exceptions.cs, src/runtime/importhook.cs, src/runtime/intern.cs, src/runtime/intern_.cs, src/runtime/intern_.tt, src/runtime/metatype.cs, src/runtime/methodbinding.cs, src/runtime/methodobject.cs, src/runtime/moduleobject.cs, src/runtime/pyscope.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
Use the intern strings map to const strings instead of creating temporary strings everytimes.
=> Intern string

.travis.yml, appveyor.yml, ci/appveyor_run_tests.ps1, setup.py, src/console/Console.15.csproj, src/embed_tests/Python.EmbeddingTest.15.csproj
.NET Core 2.0 is no longer supported. This moves tests to .NET Core 3.1 LTS, which should be supported [until Dec 2022](https://dotnet.microsoft.com/platform/support/policy/dotnet-core).
=> Use .NET Core 3.1 LTS for tests (instead of 2.0)

CHANGELOG.md, src/runtime/classmanager.cs, src/tests/test_interface.py
Allows users to call `ToString`, `GetHashCode` and `GetType` on objects wrapped in interface objects.
No
No
=> Ensure methods of Object are also available on interface objects

CHANGELOG.md, src/runtime/BorrowedReference.cs, src/runtime/NewReference.cs, src/runtime/arrayobject.cs, src/runtime/clrobject.cs, src/runtime/managedtype.cs, src/runtime/runtime.cs, src/tests/test_array.py
This handles a few new argument combinations in `tp_new` of .NET array types:
1. A single integer to create a one-dimensional array of specified size.
2. Multiple integers passed as arguments (e.g. `Array[T](3,5,7)`) to create a multidimensional array.
It processes all exceptions specified in https://docs.microsoft.com/en-us/dotnet/api/system.array.createinstance?view=net-5.0#System_Array_CreateInstance_System_Type_System_Int64___
fixes https://github.com/pythonnet/pythonnet/issues/251
-   [x] Updated the …
=> Allow creating new .NET arrays from Python using Array[T](dim1, dim2,…) syntax

.editorconfig, CHANGELOG.md, setup.py, src/runtime/Python.Runtime.15.csproj, src/runtime/Python.Runtime.csproj, src/runtime/runtime.cs
This determines the value for `Runtime.UCS` at runtime instead of using compile-time defines, removing the need for separate builds of `Python.Runtime`.
N/A
`PyUnicode_GetMax` is deprecated, but preserved for compatibility.
=> Detect the size of wchar_t (aka Runtime.UCS) at runtime using PyUnicode_GetMax

CHANGELOG.md, src/runtime/methodbinder.cs, src/tests/test_method.py
Parameters marked with `ParameterAttributes.Out` (aka `[Out]`) are no longer returned in addition to the regular method return value (unless they are passed with `ref` or `out` keyword).
As it is now possible to pass raw .NET objects to .NET methods, there's no need to marshal `[Out]` parameters back to Python manually. Python users can simply access modified object's data directly.
It was confusing to see `read, _ = stream.Read(buff, 0, buff.Length)` in the test code, as `Read` method does not really have any `out` or `ref` parameters. It also failed on some .NET implementations, as the corresponding parameter does not always have an `[Out]` attribute.
This should unblock https://github.com/pythonnet/pythonnet/pull/1307 (tests there are failing because of this difference).
Check all …
=> [Out] parameters no longer added to return tuple

.github/workflows/main.yml
Run tests on Windows and macOS via Github actions. Based on sdk-style (#1209), will rebase once that one is merged.
No, but we didn't test on macOS at all before :)
I'll leave out the test-case "Windows with Mono" for now, can be added later but requires a bit of hoop-jumping.
=> Test other Operating Systems than Linux via Github Actions

src/embed_tests/TestDomainReload.cs, src/embed_tests/TestFinalizer.cs, src/runtime/debughelper.cs, src/runtime/delegatemanager.cs, src/runtime/finalizer.cs, src/runtime/pybuffer.cs, src/runtime/pylong.cs, src/runtime/pyobject.cs, src/runtime/pyscope.cs, src/runtime/pythonexception.cs
This contains two fixes, that must go along for the tests to pass:
1. Fixed the `CollectBasicObject` and `CollectOnShutdown` tests for Mono by fixing `MakeAGarbage` function to not keep the garbage on the stack during a conservative roots scan (looks like Mono scans some variables, that are already gone).
2. Fixed the crash during runtime shutdown by further simplifying `Finalizer` to only store raw pointers to python objects instead of instances of `IPyDisposable` and thus replacing Dispose with reliable and simple `DecRef`.
This removes some functions from `Finalizer`, which previously were public, but should not have been.
=> Fixed CollectBasicObject test

src/runtime/classderived.cs
During engine shutdown all links from Python to .NET instances are severed. If an instance of CLR class defined in Python survives the shutdown (for example, a reference is stored in static field) and later gets finalized, it will attempt to severe link again, which is an invalid operation.
The fix is to check if the link has already been severed and skip that step during finalization.
Additionally in this change: refactored `MoveClrInstancesOnwershipToPython`
https://github.com/pythonnet/pythonnet/issues/1256
-   [ ] Updated the …
=> Fixed crash in finalizer of CLR types defined in Python, that survive  engine shutdown

src/runtime/runtime.cs, src/testing/methodtest.cs, src/tests/test_method.py
Use UTF8 explicitly to marshal strings towards Python C-API functions ending in `String`.
#979.
Runs fine for me both with 2.5.1 as well as current master on Linux.
=> Test for non-ASCII encoded method name

src/runtime/interop.cs, src/runtime/managedtype.cs, src/runtime/nativecall.cs
Cache the delegates to native code we've created so that when we need to
call that delegate, we don't ask for a delegate from a native pointer
(that is a delegate to managed code.)
This fixes issue #1323 .
This is needed in order for #1287 to pass the domain reload tests on Mono.
=> Fix illegal delegate usage

CHANGELOG.md, src/embed_tests/TestPyIter.cs, src/runtime/pyiter.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs
Prior to this change trying to use object returned by iterating over `PyObject` would fail after iterator is closed, because iterator would dispose previously returned objects on close/moving to the next one.
This also adds error handling for `PyIter_Next` calls, which can have other reasons to fail beyond reaching the end of collection.
=> PyIter: do not force dispose previous object upon moving to the next one

src/embed_tests/TestPythonEngineProperties.cs
Improves the test suite of Python.NET
Fixes #1335 
This change is not visible to the end user so it doesn't make sense to add it to the CHANGELOG.
=> TestPythonEngineProperties.SetPythonPath avoids corrupting the module search path for later tests

src/embed_tests/Python.EmbeddingTest.csproj, src/embed_tests/TestNativeTypeOffset.cs, src/runtime/Python.Runtime.csproj, src/runtime/native/ABI.cs
When changing Python versions, it is easy to put Python.NET into a misconfigured state.  This PR provides a helpful error message in that case.
No
This change can be tested by manually editing `configured.props` to have an incorrect `PythonInteropFile`
=> ABI.Initialize gives a helpful message when the TypeOffset interop class is not configured correctly

src/embed_tests/TestPyObject.cs, src/runtime/delegatemanager.cs, src/runtime/pyobject.cs, src/tests/test_delegate.py
When Converter.ToManaged is called in a context where it must succeed, we can get a more precise error message by calling it with setError=true.  This PR makes that change in two places.
No
There are a few other places where a similar change could be made.
=> Better error messages from PyObject.AsManagedObject and DelegateManager.TrueDispatch

.github/workflows/main.yml, CHANGELOG.md, pythonnet.sln, src/python_tests_runner/Python.PythonTestsRunner.csproj, src/python_tests_runner/PythonTestRunner.cs, src/runtime/importhook.cs
When debugging a problem such as issue #1325, it is immensely useful to have the Visual Studio debugger stop at the location of the error.  This is tricky to do with pytest, even when running pytest from Visual Studio.  Running the test via Python.Exec makes debugging simple and easy.  You don't need to re-install Python.NET every time you make a change.  You don't need to edit project options, and you don't need to figure out how to run pytest from Visual Studio.
With this change, you can just type in the name of the python test you want to debug, build the solution, and debug the new NUnit test that appears.
No
No
-   [ ] If an enhancement PR, please create docs and at best …
=> Python tests can now be debugged by running them as embedded tests within NUnit

src/domain_tests/TestRunner.cs, src/domain_tests/test_domain_reload.py, src/runtime/StateSerialization/MaybeMethodBase.cs
As Discussed in #1287, this is an extra PR to add more tests cases, and a small fix, for the reload of methods with `in`, `out` and/or `ref` parameters
...
No
...
...
=> Add more more tests for in, out and ref parameters

src/embed_tests/TestOperator.cs, src/runtime/classbase.cs, src/runtime/classmanager.cs, src/runtime/methodbinder.cs, src/runtime/operatormethod.cs
Continuation of https://github.com/pythonnet/pythonnet/pull/1324/files but specifically for comparison operators e.g. >, >=, <, == etc. based on a discussion with @tminka --- in a nutshell, we want to check each C# class for any comparison `operator` methods when calling `ClassBase.tp_richcompare`, before proceeding with the usual logic (see https://github.com/pythonnet/pythonnet/pull/294) which handles C# classes that implement an `IComparable` interface.
Would appreciate a review from @lostmsu who helped with the previous PR that this builds on. Thanks!
Closes https://github.com/pythonnet/pythonnet/issues/1312
More concrete examples can also be found in other Infer.NET tutorials e.g. having to use `op_GreaterThan` https://github.com/dotnet/infer/blob/67b4f80d97018460bcb817f76ec874d0f33f1 …
=> Support comparison operators

CHANGELOG.md, src/runtime/Python.Runtime.csproj, src/runtime/arrayobject.cs, src/runtime/converter.cs, src/runtime/pylong.cs, src/runtime/runtime.cs, src/tests/test_conversion.py, src/tests/test_method.py
Previously, when a floating point value was passed to .NET parameter of integer type, it would be silently truncated. After this change it would no longer be permitted to pass a floating point value to integer parameter.
#1342
I removed poorly-behaved `PyLong_As*` functions, as they would always implicitly convert argument to integer type, which in most cases is undesired behavior. Instead, to avoid roundtrips, `PyLong_AsSize_t` is used in most cases. The only exception is `Int64` which on 32 bit platforms is larger than `size_t`, so `PyLong_AsLongLong` function is used after explicit check for `PyLong`.
Draft because it depends on C# 9, which is not yet ready.
-   [ ] If an …
=> Disable implicit conversion from PyFloat to .NET integer types

src/runtime/converter.cs, src/tests/test_conversion.py
Fixes an oversight in #1343 that allows PyFloat to continue being converted to uint64.
Fixes the test failures in #1361
...
=> Disable implicit conversion from PyFloat to uint64

CHANGELOG.md, src/clrmodule/ClrModule.cs, src/domain_tests/test_domain_reload.py, src/embed_tests/TestPythonException.cs, src/runtime/classbase.cs, src/runtime/converter.cs, src/runtime/eventbinding.cs, src/runtime/eventobject.cs, src/runtime/exceptions.cs, src/runtime/methodbinder.cs, src/runtime/methodbinding.cs, src/runtime/pythonexception.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs, src/testing/Python.Test.csproj, src/testing/generictest.cs, src/testing/indexertest.cs, src/testing/methodtest.cs, src/tests/test_generic.py, src/tests/test_indexer.py, src/tests/test_method.py, src/tests/test_subclass.py
This change produces more specific error messages by passing setError=true to Converter.ToManaged whenever possible, such as when there is only one method in methodbinder.  To support this:
- Converter.ToManaged is fixed to obey setError consistently
- Converter.ToArray catches exceptions
- RaiseTypeError appends any existing error message
- Fixed missing information on 'No method matches given arguments' by adding the method name.
No, but it provides more information to the user when they come across issues like #1099 .  Instead of "No method matches" or "No match found" it now says `TypeError : 'int' value cannot be converted to System.Enum`
I added some failing test cases to test_array.py that should be addressed by a future PR.
-   [X] …
=> Better error messages for method argument mismatch and others

CHANGELOG.md, src/runtime/converter.cs, src/runtime/delegatemanager.cs, src/runtime/methodbinder.cs, src/testing/delegatetest.cs, src/testing/eventtest.cs, src/tests/test_delegate.py, src/tests/test_event.py
When an event handler has a ByRef argument, extra logic is needed in DelegateManager.GetDispatcher or else the program will access invalid memory and crash.
#1355 
...
=> Support ByRef arguments in event handlers

CHANGELOG.md, src/runtime/methodbinder.cs
This occured in trying to use F# code from Python. As the `.Name` property returns `null`, `ContainsKey` fails.
I don't think so.
Related documentation: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.name
I don't know if there is a way to create a C# method without a parameter name. I'll try to set up a few simple F# test-cases in the future in a separate PR (follow-up ticket: #1374).
=> ParameterInfo.Name needs to be checked for null before usage

src/runtime/pyobject.cs, src/runtime/pyscope.cs
I noticed `PyScope` ownership implementation is so-so. One of the potential reasons for the crash could be `PyScope` being improperly deallocated.
This is an attempt to fix crash in CI on Ubuntu with Python 3.9.
No
=> Simplify PyScope by delegating ownership to PyObject instance

src/runtime/intern.cs
This nulls entries in `PyIdentifier` upon runtime shutdown. If any threads are still executing C# <-> Python interop, they will see NPE instead of generic segfault, which should make it easier to debug.
=> Ensure interned strings can not be referenced after InternString.Shutdown

pythonnet/find_libpython/__init__.py
Skips checking for a linked libpython.so on Unix unless `Py_ENABLE_SHARED` is set. If it's not set, all symbols are in the base image.
#1388
...
=> Adjust static libpython detection

CHANGELOG.md, src/embed_tests/pyimport.cs, src/runtime/importhook.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs
- adds validation to `PyImportTest`
- before restoring original `__import__`, validates, that `__import__` was not replaced by a third party (only in `DEBUG` build)
- drops unsupported `_PyObject_GetDictPtr` in favor of `PyObject_GenericGetDict`
- `Length()` method now raises an exception when object does not support concept of length (was returning 0).
=> ImportHook cleanup + PyObject.Length exception

src/runtime/pythonengine.cs
`PyGILState_Release` must always be called from the same thread, that called `PyGILState_Acquire`. Which means it is illegal to try to dispose `GILState` from .NET finalizer thread.
See the following thread https://github.com/pythonnet/pythonnet/issues/1389#issuecomment-784716437
=> Allow GIL state debugging; require GILState to be properly disposed

src/runtime/platform/LibDL.cs, src/runtime/platform/LibraryLoader.cs
Newer Linux systems (Ubuntu, CentOS) do not contain `libdl.so` by default: they switched to `libdl.so.2`. So we try it first.
Also refactored `LibraryLoader` to share code between Linux and Mac (really any POSIX systems).
https://github.com/pythonnet/pythonnet/issues/1422
=> Try libdl.so.2 on Linux before libdl.so

CHANGELOG.md, Directory.Build.props, src/embed_tests/TestPyType.cs, src/runtime/TypeSpec.cs, src/runtime/clrobject.cs, src/runtime/interop.cs, src/runtime/managedtype.cs, src/runtime/metatype.cs, src/runtime/native/NativeTypeSpec.cs, src/runtime/pytype.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
This introduces a new `PyType` class (similar to `PyInt`, but for types). It can:
- wrap existing `PyObject`, that points to a type
- create a new heap type from spec (`TypeSpec` class)
It is WIP on https://github.com/pythonnet/pythonnet/issues/1033
It is related to https://github.com/pythonnet/pythonnet/pull/1196
=> PyType class, wrapper for Python types

CHANGELOG.md, src/embed_tests/TestOperator.cs, src/runtime/Codecs/EnumPyLongCodec.cs, src/runtime/classmanager.cs, src/runtime/classobject.cs, src/runtime/converter.cs, src/runtime/exceptions.cs, src/runtime/operatormethod.cs, src/runtime/opshelper.cs, src/runtime/polyfill/ReflectionPolyfills.cs, src/runtime/pylong.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs, tests/test_array.py, tests/test_conversion.py, tests/test_enum.py, tests/test_indexer.py
- enums are no longer converted to and from `PyLong` automatically https://github.com/pythonnet/pythonnet/issues/1220
- one can construct an instance of `MyEnum` from Python using `MyEnum(numeric_val)`, e.g. `MyEnum(10)`
- in the above, if `MyEnum` does not have `[Flags]` and does not have member with value `10` defined, to create `MyEnum` with value `10` one must call `MyEnum(10, True)`. Here `True` is an unnamed parameter, that allows unchecked conversion
- legacy behavior has been moved to a codec: `EnumPyLongCodec`; enums can now be encoded by codecs
- added `EnumOps` class, that implements bitwise operations on `[Flags]` enums.
#1220
-   [x] Updated the …
=> Reworked Enum marshaling

CHANGELOG.md, src/embed_tests/Codecs.cs, src/runtime/converter.cs
This disables ability to register encoders for `System.Type`.
Without this restriction encoders created in Python cause stack overflow due to repeated attempts to pass `System.Type` instance to `CanDecode`, which requires encoding the instance of `System.Type`.
https://github.com/pythonnet/pythonnet/issues/1427
=> Prevent stack overflow when an encoder is registered from Python

pythonnet/__init__.py
`find_libpython` spectacularly fails to find libpython for debug build of Python on latest Ubuntu (e.g. `apt install python3-dbg; python3-dbg`). It is also not necessary at runtime, since `Python.Runtime` can now find C API functions, since they are already loaded into the process.
Probably these:
https://github.com/pythonnet/pythonnet/issues/1388
https://github.com/pythonnet/pythonnet/issues/1412 (partially)
=> Do not call `find_libpython` during `import clr` as Python.Runtime can find it on its own

src/runtime/converter.cs, src/runtime/finalizer.cs, src/runtime/methodbinder.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs
Calls to `PyObject_Str` and `PyObject_Repr` should not be made with error set, as they may clear it. When using debug build of Python, this causes an assertion at runtime, preventing use of Python.NET.
Partial fix for https://github.com/pythonnet/pythonnet/issues/1412
=> Fixed `__cause__` on overload bind failure and array conversion

src/embed_tests/TestRuntime.cs, src/runtime/runtime.cs
The test seems to be raising errors when `threading.lock()` instance is finalized after it finishes.
https://github.com/pythonnet/pythonnet/pull/1431/checks?check_run_id=2581648554#step:13:72
=> Dispose all temporary objects in PyCheck_Iter_PyObject_IsIterable_ThreadingLock_Test

src/runtime/classbase.cs, src/runtime/classderived.cs, src/runtime/classmanager.cs, src/runtime/clrobject.cs, src/runtime/constructorbinding.cs, src/runtime/exceptions.cs, src/runtime/extensiontype.cs, src/runtime/managedtype.cs, src/runtime/metatype.cs, src/runtime/pytype.cs, src/runtime/runtime.cs, src/runtime/runtime_data.cs, src/runtime/typemanager.cs
Use `PyType` instances instead of raw pointers in `TypeManager` type cache and `ConstructorBinding` instances
This is part of an effort to clear up reference ownership story for various implementations of CLR metaclass.
No
=> Use PyType instances instead of raw pointers

src/runtime/ManagedTypes.cd, src/runtime/constructorbinding.cs, src/runtime/eventbinding.cs, src/runtime/eventobject.cs, src/runtime/extensiontype.cs, src/runtime/methodbinding.cs, src/runtime/methodobject.cs, src/runtime/moduleobject.cs, src/runtime/native/TypeOffset.cs, src/runtime/overload.cs
This replaces inheritance of `tp_dealloc` and `tp_clear` functions using slots with regular virtual functions on C# side that makes it easier to reason about.
=> Refactoring of tp_clear and tp_dealloc

src/runtime/constructorbinding.cs, src/runtime/eventbinding.cs, src/runtime/eventobject.cs, src/runtime/extensiontype.cs, src/runtime/methodbinding.cs, src/runtime/methodobject.cs, src/runtime/moduleobject.cs, src/runtime/overload.cs
This replaces inheritance of `tp_clear` function using slot with regular virtual function `Clear` on C# side that makes it easier to reason about.
=> Refactoring of tp_clear

src/runtime/pythonengine.cs, src/runtime/runtime.cs
This avoids segfault when CLR (in particular Mono) is unloaded before Python stops.
1. Added a handler to `AppDomain.ProcessExit`, that fires in the situations like this instead of `AppDomain.DomainUnload`. This allows Python.NET to remove all slots, that are implemented in C#.
2. When initialized as extension (e.g.  Python hosts CLR), release GIL acquired during shutdown so that Python finalization can resume.
This is (at least one of) the reason of CI test crashes in https://github.com/pythonnet/pythonnet/pull/1134
=> Handle ProcessExit event

src/runtime/Util.cs, src/runtime/clrobject.cs, src/runtime/debughelper.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs
When debugging code, that uses `PyObject` instances, debugger would try to execute `PyObject.ToString` to show `PyObject` values in watches window. That call causes `AccessViolationException` when the current thread does not hold global interpreter lock.
This change adds `DebuggerDisplay` attribute to `PyObject`, that makes debugger first check if GIL is held by the current thread, and only use `ToString` when it does. Otherwise, a message with object handle and a suggestion to acquire GIL is displayed.
=> Prevent crash during debugging when attempting to inspect PyObject

src/runtime/pyiter.cs
Allows creation of `PyIter` (typed) instance from `PyObject` (untyped) similar to `PyInt(PyObject)`.
=> Create PyIter from existing PyObject

src/embed_tests/Inheritance.cs, src/runtime/DefaultBaseTypeProvider.cs, src/runtime/IPythonBaseTypeProvider.cs, src/runtime/InteropConfiguration.cs, src/runtime/PythonBaseTypeProviderGroup.cs, src/runtime/PythonReferenceComparer.cs, src/runtime/StolenReference.cs, src/runtime/classmanager.cs, src/runtime/pythonengine.cs, src/runtime/pytype.cs, src/runtime/typemanager.cs
When embedding Python, host can now provide custom implementations of
`IPythonBaseTypeProvider` via `PythonEngine.InteropConfiguration.PythonBaseTypeProviders`.
When .NET type is reflected to Python, this type provider will be
able to specify which bases the resulting Python class will have.
https://github.com/pythonnet/pythonnet/issues/862
=> Allow substituting base types for CLR types (as seen from Python)

src/embed_tests/Inspect.cs, src/runtime/propertyobject.cs
Assuming
```csharp
class C
{
public int Prop { get; set; }
}
```
and Python code using it:
```python
inst = C()
print(inst.Prop)
print(C.Prop)
```
The second print call would fail prior to this change, because accessing `C.Prop` was explicitly denied.
After this change `C.Prop` will return a Python property descriptor for `Prop` property, and `inst.Prop` will behave as before.
=> Property descriptor made visible on the reflected class

CHANGELOG.md, src/runtime/typemanager.cs
Previously, Python.NET would produce confusing type names in certain scenarios (generic and/or nesting types).
=> Names of .NET types changed to better support generic types

src/embed_tests/TestPyObject.cs, src/runtime/pyobject.cs
Instead, they crashed with `ArgumentNullException` due to null pointer passed to `PyObject` constructor. Fixed by adding a check for `None`.
N/A
N/A
=> Dynamic arithmetic ops raise correct Python exception on failure

src/embed_tests/Inheritance.cs, src/runtime/classbase.cs, src/runtime/managedtype.cs, src/runtime/pytype.cs
Calls `tp_clear` (if any) of base unmanaged type when a reflected CLR object instance is cleared.
https://github.com/pythonnet/pythonnet/issues/1476
C# exceptions inherit from Python `BaseException` class, which has `tp_clear`. Prior to this change it was not called when Python deallocated them leaving dangling references to `BaseException.args` and `BaseException.__cause__`.
=> Call tp_clear of base unmanaged type

src/embed_tests/Codecs.cs, src/runtime/pyobject.cs
Prior to this change there was a discrepancy between `.As<object>()` and `.AsManagedObject(typeof(object))`: the former would bypass all registered custom decoders.
=> Allow decoders affect `PyObject.As<object>()`

src/embed_tests/TestInterrupt.cs, src/runtime/pythonengine.cs
Also: avoid using `dynamic` in `GetPythonThreadID`
This should put us to peace in regards to this warning in CI on MacOS X Python 3.7:
```
Exception ignored in: <module 'threading' from '/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py'>
Traceback (most recent call last):
File "/Users/runner/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/threading.py", line 1292, in _shutdown
assert tlock.locked()
AssertionError: 
```
It happens when the main Python thread never imports `threading` module, while secondary threads do.
=> Added workaround for warning in `threading` module after `TestInterrupt`

src/embed_tests/pyinitialize.cs, src/runtime/classmanager.cs
https://github.com/pythonnet/pythonnet/issues/1561
Long term we should switch `ManagedType` and other classes, that hold long-lived references to Python objects to use `PyObject`. This would make any code, that uses them refcount-balanced automatically.
See #1562
=> `ClassManager` illegally decrefed `ClassObject`'s refcount on shutdown

src/embed_tests/Codecs.cs, src/runtime/Python.Runtime.csproj, src/runtime/Util.cs, src/runtime/pythonengine.cs, src/runtime/pythonexception.cs, src/runtime/resources/interop.py, src/runtime/runtime.cs
Added new Python class `clr.interop.PyErr` with optional `type`, `value`, and `traceback` attributes. User can register decoders for it, that would let them decode instanceless (and even typeless) Python exceptions.
These decoders will be invoked before the regular exception instance decoders.
This allows decoding exceptions before they are normalized (which is not always possible).
=> Allow decoding instanceless exceptions

src/runtime/classbase.cs, src/runtime/managedtype.cs, src/runtime/runtime.cs, tests/test_subclass.py
=> Do not clean `tpHandle` in `ClassBase.tp_clear` - it might be used in `tp_dealloc`

src/runtime/extensiontype.cs, src/testing/methodtest.cs, tests/test_method.py
This allows Python to hook implementations of .NET methods in-place. Some Python libraries do that (in particular TensorFlow) for validation/tracking purposes.
=> Allow Python to overwrite .NET methods

src/runtime/converter.cs, src/runtime/delegatemanager.cs, src/runtime/importhook.cs, src/runtime/runtime.cs
Remove risky finalization code from `Dispatcher`, and use reference types
=> Simplify `Dispatcher`

CHANGELOG.md, src/embed_tests/Codecs.cs, src/embed_tests/TestConverter.cs, src/runtime/Util.cs, src/runtime/classderived.cs, src/runtime/converter.cs, src/runtime/pydict.cs, src/runtime/pyint.cs, src/runtime/pyiterable.cs, src/runtime/pynumber.cs, src/runtime/pyobject.cs, src/runtime/pysequence.cs, src/runtime/pythonexception.cs, tests/test_array.py, tests/test_conversion.py, tests/test_field.py, tests/test_generic.py, tests/test_method.py, tests/test_module.py
This removes the following conversions:
`PyInt` -> `int32` (when trying to convert to `object` only)
.NET arrays and collections -> Python `list` (due to mutability)
Additionally, `PyObject` no longer implements `IEnumerable<PyObject>`, as not all python objects are iterable. Instead, a new class `PyIterable` is added.
=> Disable implicit conversions that might lose information

src/embed_tests/pyimport.cs, src/runtime/assemblymanager.cs, src/runtime/moduleobject.cs
Before trying to load an assembly by its full path we were trying to call `Assembly.Load` on it. `Assembly.Load` interprets its argument as a valid `AssemblyName`. However full paths are not valid assembly names, so that call would throw `FileLoadException`, which we did not handle.
The fix is to separately try to parse input string into an `AssemblyName` and only try `Assembly.Load` when it succeeds.
https://github.com/pythonnet/pythonnet/commit/9d5f57973bafb9086bb7664547abbd73c9fabc3c#commitcomment-57061082
Related: https://github.com/pythonnet/pythonnet/issues/1514
=> Fixed `FileLoadException` when trying `clr.AddReference('/full/path.dll')`

README.rst, src/embed_tests/TestPythonEngineProperties.cs, src/runtime/platform/LibraryLoader.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs
This handles failure to load internal `Delegates` type due to misconfigured `PythonDLL`, which used to raise `TypeLoadException` whose `InnerException` would give users the details. Unfortunately, some users do not bother to go as far as to look into the `InnerException`, and instead go straight to GitHub and report "a bug".
This change handles that `TypeLoadException` and rethrows it as `BadPythonDllException` in major entry points, which makes looking into `InnerException` unnecessary, hopefully reducing the number of "bugs"
-   [x] Updated …
=> Raise `BadPythonDllException`  instead of confusing `TypeLoadException` when `PythonDLL` was not configured properly

CHANGELOG.md, src/embed_tests/Inspect.cs, src/runtime/exceptions.cs, src/runtime/methodbinding.cs, src/runtime/methodobject.cs, src/runtime/runtime.cs
This implements `__name__` and `__signature__` Python members for reflected .NET methods, that enables them to be analyzed with `inspect` module.
N/A
Some Python libraries validate passed callables by using `inspect` module. This makes it possible for .NET methods to pass this kind of validation.
=> __name__ and __signature__ for .NET methods

src/embed_tests/ClassManagerTests.cs, src/runtime/classmanager.cs, src/runtime/typemanager.cs
Without this fix attempting to use a nested .NET class that derives from its parent would cause a crash due to false mutual dependency.
https://github.com/pythonnet/pythonnet/issues/1414
=> When reflecting nested types, ensure their corresponding `PyType` is allocated

CHANGELOG.md, src/embed_tests/TestPyObject.cs, src/runtime/pyobject.cs
Prior to this change `PyObject.GetAttr(name, default)` would ignore any exceptions, including ones unrelated to missing attribute. For example (hypothetically) `PyObject` is a file, and you call `file.GetAttr("len", 0)`, it would return `0` on I/O error even though `file` object actually has `len` attribute.
I marked the method obsolete, as even now when we restrict ignored errors to `AttributeError` and derived types, the behavior of this method still going to be misleading in some scenarios. For example,
```python
class RaisesAttrErr:
@property
def prop(self): raise AttributeError
class OK:
def __init__(self, impl):
self._impl = impl
@property
def existing_prop(self): return self._impl.prop
```
```csharp
PythonEngine.Eval("OK(RaisesAttrErr())").GetAttr("existing_prop", 0)
// returns 0 …
```
=> Safer `GetAttr(name, default)`

CHANGELOG.md, src/embed_tests/Codecs.cs, src/runtime/Codecs/DecoderGroup.cs, src/runtime/Codecs/EnumPyIntCodec.cs, src/runtime/Codecs/IterableDecoder.cs, src/runtime/Codecs/ListDecoder.cs, src/runtime/Codecs/SequenceDecoder.cs, src/runtime/Codecs/TupleCodecs.cs, src/runtime/converterextensions.cs
`IPyObjectDecoder.CanDecode` first parameter (objectType) type changed from `PyObject` to `PyType`
Related: https://github.com/pythonnet/pythonnet/issues/1539
=> Changed signature of `IPyObjectDecoder.CanDecode`

CHANGELOG.md, README.rst, src/embed_tests/NumPyTests.cs, src/embed_tests/TestConverter.cs, src/python_tests_runner/PythonTestRunner.cs, src/runtime/converter.cs, src/runtime/pyobject.cs, tests/test_conversion.py, tests/test_delegate.py, tests/test_field.py, tests/test_indexer.py, tests/test_module.py
Disabled using `__float__` during implicit conversions to .NET floating-point types. Explicit conversion is possible in Python with `float(val)` and .NET with `(double)dynamicPyObj`.
Arbitrary Python objects are no longer implicitly converted to .NET `bool` type.
this is a continuation of https://github.com/pythonnet/pythonnet/pull/1568
related to https://github.com/pythonnet/pythonnet/issues/1539
=> Disabled `float` and `bool` implicit conversions

.github/workflows/main.yml, .github/workflows/nuget-preview.yml, Directory.Build.props, pythonnet.sln, src/console/Console.csproj, src/embed_tests/Python.EmbeddingTest.csproj, src/python_tests_runner/Python.PythonTestsRunner.csproj, src/runtime/Python.Runtime.csproj, src/testing/Python.Test.csproj, tests/conftest.py
.NET 5 that we use expires in May 2022. For the new version we should use LTS if possible.
Also, new goodies in C#!
=> Use .NET 6.0 LTS and C# 10

Directory.Build.props
Should supersede https://github.com/pythonnet/pythonnet/pull/1615
=> Update NonCopyableAnalyzer to latest version with our changes upstreamed

CHANGELOG.md, src/embed_tests/StateSerialization/MethodSerialization.cs, src/runtime/Reflection/ParameterHelper.cs, src/runtime/StateSerialization/MaybeMethodBase.cs, src/runtime/runtime_data.cs
The old method matching code never worked for generic methods because their parameter types did not have assembly qualified names.
The new method explicitly checks generic parameters.
It also allows reloading of private methods, which can be exposed to Python via reflection or delegate binding.
This is part of work to remove all shutdown modes (only Reload will remain), that ensures, that internal methods are always successfully reloaded.
=> Match generic and private methods upon runtime reload

setup.py
Before `pythonnet` 3.0 is finally released, we should bump clr-loader to 1.0.
Bump the required clr-loader version.
Maybe #1617 was already fixed in `clr-loader`, we should in any case follow that one for now.
=> Require newest available clr-loader

src/runtime/native/PyGILState.cs
CPython uses a bare `enum` here, both of .NET and C default to `int`
enums, so this should be closer to the truth if no special compile
options are used.
Attempts to fix #1606.
=> Fix the PyGILState_STATE type

src/runtime/typemanager.cs, tests/utils.py
Also makes the type names a bit more Python-esque. The `clr._internal`
module doesn't exist, but that is no difference to the previous setup.
...
...
...
=> Fix warning regarding undefined __module__ on GC Offset Base

src/runtime/pythonengine.cs, src/runtime/runtime.cs
This removes the need to ensure that all .NET objects references by Python when app stops are serializable. Also saves some time.
=> When process is exiting, there's no need to save live .NET objects

src/embed_tests/Inheritance.cs, src/runtime/ReflectionUtil.cs, src/runtime/propertyobject.cs
.NET `PropertyInfo.GetMethod` would not return base non-overridden accessor for a partially overridden property (e.g. only setter overridden)
Because of that when constructing `PropertyObject` we scan base classes to find base accessor (if any).
fixes https://github.com/pythonnet/pythonnet/issues/1455
This might have performance implications due to replacement of `PropertyInfo.GetValue` with `getter.Invoke` (not tested)
No need to serialize accessors - they can be reconstructed from the `PropertyInfo`
=> Fixed accessing partially overriden properties from Python

src/runtime/methodbinder.cs, src/runtime/methodbinding.cs, src/runtime/methodobject.cs, src/testing/methodtest.cs, tests/test_generic.py
Prior to this change if method had multiple generic overloads, only 1 of them could be matched (whichever one reflection would return first)
Now `MethodBinder.MatchParameters` returns all matching generic overloads, not just the first one.
fixes https://github.com/pythonnet/pythonnet/issues/1522
=> Improved support for generic method overloading

src/runtime/runtime.cs
This prevents the Python DLL from being unloaded after `Py_NoSiteFlag` is set.
fixes https://github.com/pythonnet/pythonnet/issues/1517
=> Use Delegates to access Py_NoSiteFlag

src/runtime/classmanager.cs, src/runtime/native/ITypeOffsets.cs, src/runtime/native/TypeOffset.cs, src/runtime/operatormethod.cs, src/runtime/opshelper.cs, src/testing/enumtest.cs, tests/test_enum.py
Added `EnumOps.__int__`, that provides `__int__` method for type dictionaries of reflected enum types.
implements https://github.com/pythonnet/pythonnet/issues/1585
=> Provide `__int__` instance method on enum types to support `int(Enum.Member)`

src/embed_tests/TestPyBuffer.cs, src/runtime/bufferinterface.cs, src/runtime/finalizer.cs, src/runtime/pybuffer.cs, src/runtime/pyobject.cs, src/runtime/runtime.cs
- better finalizer, that actually calls `PyBuffer_Release`
- improved input parameter handling for common routines
- added support for copying data to/from large Python buffers
fixes https://github.com/pythonnet/pythonnet/issues/1556
=> Cleanup `PyBuffer` a bit

CHANGELOG.md, src/runtime/classderived.cs, src/runtime/codegenerator.cs, src/runtime/delegatemanager.cs, src/testing/interfacetest.cs, tests/test_interface.py
This supports overriding virtual .NET methods that have `out` or `ref` parameters from Python.
The new code is emitted to
1. unpack the tuple returned from Python to extract new values for byref parameters and modify args array correspondingly
2. marshal those new values from the args array back into arguments in generated IL
fixes https://github.com/pythonnet/pythonnet/issues/1481
Related to https://github.com/pythonnet/pythonnet/pull/1364
=> Support for byref parameters when overriding .NET methods from Python

AUTHORS.md, CHANGELOG.md, src/runtime/MethodBinder.cs, tests/test_method.py
Current method binder code needs cleanup. There is an active issue with pythonnet failing to find the appropriate overload when the method signature includes `out` parameters e.g. `SomeMethod(int a, out int b)`. Current workaround is to call the method by providing bogus value for the `out` parameter e.g. `SomeMethod(1, 0)` instead of `SomeMethod(1)`
This PR pushes a temporary fix for this problem until the binder code is cleaned up. The change is intentionally minimal.
Not sure. Can not find anything related to this by looking at open issue titles
No
-   [x] Updated the …
=> Temporary fix method binder for out parameters

src/testing/exceptiontest.cs, tests/test_exceptions.py
Originally from PR #1402. The underlying bug is now fixed, but the tests
are still applicable.
Possibly #1371 (it may have been fixed already by another PR)
=> Add tests for exception leaking.

src/embed_tests/dynamic.cs, src/runtime/PythonTypes/PyObject.cs
When the object is a Python iterable
Enables `foreach` loops over dynamic `PyObject` instances
https://github.com/pythonnet/pythonnet/issues/1680
=> Allow dynamic `PyObject` conversion to `IEnumerable`

CHANGELOG.md, src/embed_tests/Codecs.cs, src/embed_tests/TestPyObject.cs, src/runtime/InternString.cs, src/runtime/Py.cs, src/runtime/PythonTypes/PyObject.cs
passing Python objects to unsuspecting .NET methods, that accept `object` would lead to crash if those methods try to use standard .NET `System.Object` members without acquiring the Python GIL first.
fixes https://github.com/pythonnet/pythonnet/issues/1642
=> Make methods of `PyObject` inherited from its base .NET classes GIL-safe

CHANGELOG.md, src/embed_tests/TestConverter.cs, src/embed_tests/TestPyInt.cs, src/runtime/Converter.cs, src/runtime/PythonTypes/PyInt.cs, src/runtime/Runtime.cs, src/runtime/Util/Util.cs
Adds various conversions between `PyInt` and `System.Numerics.BigInteger`.
fixes https://github.com/pythonnet/pythonnet/issues/1642#issuecomment-1058412759
=> Support for `BigInteger` (C#) <-> `PyInt`

pythonnet.sln, pythonnet/__init__.py, src/runtime/Runtime.cs, src/runtime/TypeManager.cs, src/runtime/Types/ClassDerived.cs, src/runtime/Types/ModuleObject.cs, tests/test_engine.py
Before this fix slots of reflected types were not released to Python defaults leaving Python referencing managed code after managed runtime has already shut down.
In the original bug, the runtime in question is Mono after `mono_jit_cleanup`
https://github.com/pythonnet/pythonnet/issues/1683
=> On shutdown from Python release all slot holders

src/embed_tests/TestInstanceWrapping.cs, src/runtime/Runtime.Delegates.cs, src/runtime/Runtime.cs, src/runtime/Types/ClassBase.cs
According to [official documentation](https://docs.python.org/3/extending/newtypes.html#weak-reference-support) for defining extension types, if they are to support weak references, they must clear weak reference list associated with the instance in `tp_clear`.
This was missed when https://github.com/pythonnet/pythonnet/pull/1267 was superseded.
P.S. without the fix corresponding test would crash with segfault due to an attempt to dereference an object that no longer exists via a weak reference to it.
N/A
=> Clear weakref list when reflected object is destroyed

src/embed_tests/ExtensionTypes.cs, src/runtime/Types/ExtensionType.cs, src/runtime/Types/MetaType.cs
Extension types were missed in https://github.com/pythonnet/pythonnet/pull/1758
Clears weakref list in extension type instances when they are destroyed
=> Clear weak reference list when an extension type is destroyed

src/runtime/Converter.cs, src/runtime/PythonTypes/PyFloat.cs, src/runtime/PythonTypes/PyInt.cs, src/runtime/PythonTypes/PyObject.IConvertible.cs, src/runtime/PythonTypes/PyString.cs, tests/test_conversion.py
Implements the [IConvertible](https://docs.microsoft.com/en-us/dotnet/api/system.iconvertible) interface for `PyObject` instances.
Should fix #1755.
...
-   [X] If an enhancement PR, please create docs and at best an example
=> Implement IConvertible on PyObject

.github/workflows/main.yml
I suspect the issue is actually with Mono GC and the relatively new mode of suspending threads, which has a few (closed) bugs against it, complaining about hangs. In many of those bugs (you can find them [here](https://github.com/mono/mono/issues?q=is%3Aissue+MONO_THREADS_SUSPEND+hangs)) switching to the old `preemptive` mode works around the issue. I tried it for our tests, and it seems to solve it too.
The issue also vaguely mentioned in https://www.mono-project.com/docs/advanced/runtime/docs/coop-suspend/#thread-startfinish-still-bad
So the fix is to simply set `MONO_THREADS_SUSPEND` to `preemptive` in CI before running tests in Mono.
Fixes https://github.com/pythonnet/pythonnet/issues/1766
This workaround seems to solve the issue on my local machine as well as in CI. I did 5+ CI full …
=> Work around potential Mono bug, that hangs the runtime when new threads start

src/runtime/Codecs/EnumPyIntCodec.cs, tests/test_codec.py
A boxed enum value can't be casted directly to an integer, but using `System.Convert`
functions instead works fine.
...
...
...
=> Fix enum codec

CHANGELOG.md, src/runtime/PythonEngine.cs, src/runtime/PythonException.cs
Shutting down runtime when the Python error indicator is set has unpredictable behavior.
=> Disallow runtime shutdown when the Python error indicator is set

CHANGELOG.md, src/runtime/ClassManager.cs, src/runtime/Mixins/collections.py, src/runtime/TypeManager.cs, src/runtime/Types/ClassObject.cs, src/runtime/Types/ClrObject.cs, src/runtime/Types/GenericType.cs, src/runtime/Types/MethodObject.cs, src/runtime/Types/ReflectedClrType.cs, tests/test_collection_mixins.py
This has individual commits for:
1. bad name generation for nested classes which caused the type of `Dictionary.Keys` to be confused with the `Dictionary` itself
2. quality of life change, that allows cast `Generic.IEnumerable(obj)`, which previously required the generic type argument to be specified. E.g. `Generic.IEnumerable[String](obj)` was required
3. collection mixins now cast objects to corresponding interfaces when the interfaces are implemented privately
fixes https://github.com/pythonnet/pythonnet/issues/1785
@Martin-Molinero
=> Multiple fixes related to Dictionary.Keys bug

CHANGELOG.md, src/runtime/PythonEngine.cs, tests/test_engine.py
fixes https://github.com/pythonnet/pythonnet/discussions/1724
=> `Min`/`MaxSupportedVersion` and `IsSupportedVersion` on `PythonEngine`

CHANGELOG.md, src/embed_tests/dynamic.cs, src/runtime/PythonTypes/PyObject.cs, src/runtime/Runtime.cs
Also fixed unhandled Python errors during comparison attempts
For `==` and `!=` operators in C# to use Python equality `PyObject` must implement `operator ==` and `operator !=`. C# ignores `TryBinaryOperation` implementation for equality comparisons.
The "also" part clears Python error when comparison can not be performed.
https://github.com/pythonnet/pythonnet/issues/1848
=> Implemented dynamic equality and inequality for `PyObject` instances

src/runtime/Converter.cs, src/runtime/Runtime.cs, src/runtime/Types/ClassObject.cs, src/testing/conversiontest.cs, tests/test_conversion.py
Allows creating an `IntPtr` from Python. This is currently impossible, because we rely on automatic conversion (as `IntPtr` is a primitive type) while we don't actually implement one for this type (rightly so!).
The relevant code section is:
https://github.com/pythonnet/pythonnet/blob/87d4db92f6da00b4be27b842ac2ba9875569e04d/src/runtime/Types/ClassObject.cs#L73-L89
#1116 
...
-   [ ] Updated the …
=> Fix (U)IntPtr construction

src/runtime/ClassManager.cs, tests/test_docstring.py, tests/test_enum.py
Fix missing docstring for types with custom constructors
...
...
...
=> Fix docstring for directly constructed types

src/runtime/Finalizer.cs, src/runtime/Native/NewReference.cs, src/runtime/Runtime.cs, tests/test_constructors.py
`NewReference.Move` used to call `NewReference` constructor that increfs the handle. However, `Move` semantics must be of transferring the ownership: the reference count should stay, ownership transferred to the new instance.
https://github.com/pythonnet/pythonnet/issues/1872
=> Fixed a leak in `NewReference.Move`

pythonnet/__init__.py, tests/test_import.py
There are small typos in:
- pythonnet/__init__.py
- tests/test_import.py
Fixes:
- Should read `splitted` rather than `splited`.
- Should read `loaded` rather than `laoded`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

CHANGELOG.md, src/runtime/Converter.cs, tests/test_conversion.py
Disabled implicit conversion from Python objects implementing sequence protocol to .NET arrays when the target .NET type is `System.Object`. The conversion is still attempted when the target type is a `System.Array`.
Many Python types implement sequence protocol. In many cases such conversion looses too much important data.
fixes https://github.com/pythonnet/pythonnet/issues/1900
=> Disabled implicit seq to array conversion

src/runtime/Native/ITypeOffsets.cs, src/runtime/Native/TypeOffset.cs, src/runtime/Types/ClassBase.cs, src/runtime/Types/OperatorMethod.cs, tests/test_conversion.py
=> Explicit float and int conversion for builtin types

src/runtime/Native/ITypeOffsets.cs, src/runtime/Native/TypeOffset.cs, src/runtime/Types/ClassBase.cs, src/runtime/Types/OperatorMethod.cs, src/runtime/Util/OpsHelper.cs, tests/test_conversion.py
Fills slot for `__index__` as a follow up to #1904. In Python >= 3.10, use of `__int__` for quite a few conversion cases has been removed.
-/-
...
=> Fill nb_index slot for integer types

src/runtime/Native/LibraryLoader.cs
Current process handle can be closed before we try to enumerate process modules because we do not keep an instance of `Process` alive.
fixes https://github.com/pythonnet/pythonnet/issues/1939
credits to @sdao for discovering the bug and suggesting a fix
=> Fixed use of the process handle after Process instance is garbage collected

Directory.Build.props, pythonnet.sln, tests/test_module.py
Prior to this change `clr.__version__` would have a newline character at the end, e.g. `'3.0.0-rc3\n'`
=> Fixed new line character at the end of informational version

MANIFEST.in, pyproject.toml, pythonnet/__init__.py, tests/conftest.py
- Bump clr-loader dependency to 0.2.0 and adjust interface, allows to load a .NET Core Python.NET by just setting `PYTHONNET_RUNTIME=coreclr` or `from pythonnet import set_runtime; set_runtime("coreclr")`
- Improve error message if the runtime fails to load
#1868
=> Config-less CoreCLR and improved runtime load message

src/runtime/Converter.cs, src/runtime/Runtime.cs, tests/test_method.py
Uses `__float__` when available if a Python object is passed to a function with a `Double` or `Single` parameter.
#1833
This is not yet supported for integer types, which would use `__int__`
or `__index__` (for Python >=3.10), as the respective logic is for some
reason only implemented for `AsLongLong` and `AsLong`, not for the
unsigned counterparts and also not for the `AsSize_t` variants that we
are using.
-   [ ] Updated the …
=> Implicit float conversion in function calls

CHANGELOG.md, src/embed_tests/Events.cs, src/runtime/Finalizer.cs, src/runtime/PythonTypes/PyObject.cs, src/runtime/Util/CodeGenerator.cs, src/runtime/Util/EventHandlerCollection.cs
The objects were leaking because they were kept as keys in a dictionary, that stored event handlers corresponding to object.
This change ensures that when the last handler is removed from an object, the object is removed from that dictionary.
fixes https://github.com/pythonnet/pythonnet/issues/1972
=> Delete target object from event handler collections when it has no more event handlers

src/embed_tests/Codecs.cs, src/runtime/Converter.cs, src/runtime/Runtime.cs
When a Python instance needs to be converted to `System.Object`, and the Python type is derived from one of the primitives (e.g. `numpy.float64` is derived from `float`), allow a custom decoder to override the default behavior (which would have been converting to `System.Double`).
It addresses the primary concern of https://github.com/pythonnet/pythonnet/issues/1957
=> Allow decoders to decode Python types derived from primitives

CHANGELOG.md, src/embed_tests/TestPyInt.cs, src/runtime/PythonTypes/PyInt.cs
`BigInteger(byte[])` constructor uses the sign bit in the first byte.
Since we explicitly handle the sign, the fix is to prepend a zero byte to the number, which does not change it, but ensures sign bit is zero.
fixes https://github.com/pythonnet/pythonnet/issues/1990
=> Fix positive `PyInt` converted to negative `BigInteger`

CHANGELOG.md, src/python_tests_runner/PythonTestRunner.cs, src/runtime/Types/ClassDerived.cs, src/testing/generictest.cs, tests/test_subclass.py
- If a method is virtual AND generic, it cannot be overridden by the python class. Hence the method call is deferred to the base class.
- Added a unit test which verifies this behavior is now working.
Close #1776 
-   [X] If an enhancement PR, please create docs and at best an example
-   [X] Ensure you have signed the [.NET Foundation CLA](https://cla.dotnetfoundation.org/pythonnet/pythonnet)
=> 1776 Generic Virtual Method Causes Invalid Program: Fix + test

.github/workflows/ARM.yml, requirements.txt
`setuptools` 66+ removed support for some formats of package version suffixes.
This change skips forced `setuptools` upgrade on our runners at least until Ubuntu changes their package name format.
[This pull request](https://github.com/pythonnet/pythonnet/pull/2079) can not proceed due to this failure
see https://github.com/pypa/setuptools/issues/3772
=> Workaround for Ubuntu-provided package version being unsupported

CHANGELOG.md, src/python_tests_runner/PythonTestRunner.cs, src/runtime/Runtime.cs, src/runtime/StateSerialization/MaybeType.cs, src/runtime/TypeManager.cs, src/runtime/Types/ClassDerived.cs, src/runtime/Types/MetaType.cs, src/runtime/Types/ReflectedClrType.cs, src/testing/classtest.cs, tests/test_subclass.py
Added support for multiple inheritance when inheriting from one base class and/or multiple interfaces.
Added a unit test verifying that it works with a simple class and interface. This unit test would previously have failed since multiple types are in the class super class list.
Close #1783
-   [X] If an enhancement PR, please create docs and at best an example
-   [X] Ensure you have signed the [.NET Foundation CLA](https://cla.dotnetfoundation.org/pythonnet/pythonnet)
=> 1783 Implement Interface And Inherit Class

AUTHORS.md, CHANGELOG.md, src/embed_tests/TestPyBuffer.cs, src/runtime/PythonTypes/PyBuffer.cs
PyBuffer throws `System.ArgumentOutOfRangeException` when trying to use `GetBuffer()` with anything other than `PyBUF.SIMPLE` since the `Marshal.Copy` calls had a typos so it was trying to copy `shape`, `strides`, and `suboffsets` as arrays that were the full length of the source array instead of length `ndim`.
no
...
-   [ ] Ensure you have signed the [.NET Foundation CLA](https://cla.dotnetfoundation.org/pythonnet/pythonnet) <- doesn't seem to be working
=> Fix `GetBuffer` throwing `ArgumentOutOfRangeException`

doc/source/dotnet.rst
Changes in documentation. PyScope data type not found. Py.CreateScope() returns the variable of type PyModule.
...
No
...
=> change PyScope to PyModule

CHANGELOG.md, src/runtime/Types/ClassObject.cs, tests/test_enum.py
Proposal to fix #2238
```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr; import System
>>> System.DayOfWeek.Monday
<System.DayOfWeek object at 0x0000024D5BAC7300>
```
```
IronPython 2.7.4 (2.7.0.40) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import System
>>> System.DayOfWeek.Monday
System.DayOfWeek.Monday
```
```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr; import System
>>> System.DayOfWeek.Monday
DayOfWeek.Monday
```
-   [x] Make sure to include one …
=> use enum name in repr

src/runtime/CollectionWrappers/IterableWrapper.cs
**System.AccessViolationException** occurs when iteration quits in the middle of list before reaching the end.
-   Pythonnet version: 3.0.3
-   Python version: 3.12.0
-   Operating System: Windows 11
-   .NET Runtime: .NET Framework 4.8
I'm trying to pass a list from python to .NET method via List Codec. 
```python
mylist = ["a","b","c"]
dotnet.method( mylist )
```
Conversion(decode) is successful and mylist is wrapped by **ListWrapper**.
.NET code receives the list like this. 
```csharp
void method( IList<string> mylist )
{
mylist.First( s => s == "b" ); // <- here the crash with System.AccessViolationException
}
```
Using Enumerator of **mylist**, if enumerated to the end of the list, nothing bad happens.
However if iteration didn't go to the end of the list, AccessViolationException is …
=> When IterableWrapper iterates up to the middle of list, System.AccessViolationException occurs.

AUTHORS.md, CHANGELOG.md, src/embed_tests/TestOperator.cs, src/runtime/ClassManager.cs, src/runtime/MethodBinder.cs, src/runtime/Types/MethodBinding.cs, src/runtime/Types/MethodObject.cs, src/runtime/Types/OperatorMethod.cs
Reverse operators were not implemented correctly for C# types which resulted in Recursion errors when embedding C# in Python. Changed the model binding process to add reverse operators for all applicable types. Added a flag to MethodBinder that signals the operation is a reversed operation and that the arguments to the operator needs to be reversed.
Added tests and an wrapper object for int without overloaded operator methods and a wrapper codec to test the reverse operations (and forward operator on the same type for safety).
...
This should resolve #2240.
...
...
-   [ ] Ensure you have signed the [.NET …
=>  #2240 Recursion error when doing reversed python operations on C# types

CHANGELOG.md, src/embed_tests/TestConverter.cs, src/runtime/Converter.cs
Added `ToPythonAs<T>()`  extension method to allow for explicit conversion using a specific type
The existing `ToPython()` extension always uses current object type. There are scenarios though where objects have to be explicitly represented as their base types or interfaces. For example, `42.ToPython()` produces Python `int`, but there's currently no easy way from C# to pass `42` as `IConvertible` so that Python could call the `IConvertible` members.
The new extension can be used for this purpose: `42.ToPythonAs<IConvertible>()` will return a `PyObject` that has all `IConvertible` members.
fixes https://github.com/pythonnet/pythonnet/issues/2311
N/A
-   [x] If an enhancement …
=> Added `ToPythonAs<T>()` 

CHANGELOG.md, src/embed_tests/TestPyFloat.cs, src/embed_tests/TestPyInt.cs, src/embed_tests/TestPyString.cs, src/runtime/PythonTypes/PyFloat.IComparable.cs, src/runtime/PythonTypes/PyFloat.cs, src/runtime/PythonTypes/PyInt.IComparable.cs, src/runtime/PythonTypes/PyInt.cs, src/runtime/PythonTypes/PyObject.cs, src/runtime/PythonTypes/PyString.cs
`IComparable` and `IEquatable` implementations for `PyInt`, `PyFloat`, and `PyString` for primitive .NET types
Let's one do `PyInt.CompareTo(42)` and similar things
N/A
Should we take GIL in these methods? Might be useful for `Array.Sort` when called from Python.
On a more general topic: should we have a way for Python to call a .NET method and have it not release the GIL for compatibility with 3rd party (to Python.NET) libraries that assume they can call back any methods they wish at any time. Because having explicit GIL acquisition in `CompareTo` to use with `Array.Sort` would kill performance. E.g. something like:
```python
with clr.HoldGIL():
Array.Sort(dotnet_array_of_python_objects)
```
-   [x] Make sure to include one or more tests …
=> `IComparable` and `IEquatable` implementations

src/embed_tests/TestPyType.cs, src/runtime/Loader.cs, src/runtime/Native/CustomMarshaler.cs, src/runtime/Native/NativeTypeSpec.cs, src/runtime/PythonTypes/PyType.cs, src/runtime/Runtime.cs, src/runtime/Util/Encodings.cs, tests/test_conversion.py
Use non-BOM encodings for both C#->Python and Python->C#, as the byteorder is always the native one and the BOM is neither never or always used.
Fixes #2369.
=> Use non-BOM encodings

CHANGELOG.md, src/runtime/StateSerialization/NoopFormatter.cs, src/runtime/StateSerialization/RuntimeData.cs, tests/domain_tests/TestRunner.cs, tests/domain_tests/test_domain_reload.py
Adds post-serialization and pre-deserialization hooks for additional customization.
This PR supersedes #1892 , offer another workaround for issues #2335 #2221 #2282 , possibly others.
This addresses @lostmsu 's comments of exposing an API instead of adding functionality
According to Unity dev answers on the Unity forums, they will implement a ring-link architecture as a replacement for domain load/unload. I have added no tests yet in this PR considering that domain load/unload is deprecated from a .NEt perspective.
https://forum.unity.com/threads/unity-future-net-development-status.1092205/page-34#post-8918231
This PR is made in my own name, I am no longer working at the company that signed the CLA for me.
-   [ ] Make sure to include one …
=> Expose serialization api

CHANGELOG.md, src/runtime/AssemblyManager.cs, src/runtime/Exceptions.cs, tests/test_module.py
User can add arbitrary strings to `sys.path`. When we probe for assemblies in `sys.path` the ones that were not valid paths caused the probing to fail, never reaching the valid ones that actually had the desired assembly.
This change handles these cases by generating a warning and continuing to probe in other directories.
fixes #2376
=> Handle bad paths in `sys.path`

CHANGELOG.md, src/runtime/ClassManager.cs, src/runtime/InternalPythonnetException.cs, src/runtime/Types/ReflectedClrType.cs
1. Fixes crash on events with no [`AddMethod`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.eventinfo.addmethod)
2. Adds `InternalPythonnetException` that can tell user what .NET type caused failure if an unexpected internal error occurs
https://github.com/pythonnet/pythonnet/discussions/2405
=> Fix crash when event does not have `Add` method and improve message for some other internal errors

AUTHORS.md, CHANGELOG.md, src/runtime/Finalizer.cs, src/runtime/Runtime.cs, src/runtime/Types/ClrObject.cs
When nulling the GC handles on shutdown the reference count of all objects pointed to by the IntPtr in the `CLRObject.reflectedObjects` are zero. This caused an exception in some scenarios because `Runtime.PyObject_TYPE(reflectedClrObject)` is called while the reference counter is at zero.
After `TypeManager.RemoveTypes();` is called in the `Runtime.Shutdown()` method, reference count decrements to zero do not invoke `ClassBase.tp_clear` for managed objects anymore which normally is responsible for freeing GC handles and removing references from `CLRObject.reflectedObjects`. Collecting objects referenced in `CLRObject.reflectedObjects` only after leads to an unstable state in which the reference count for these object addresses is zero while still maintaining them to be used for further …
=> Fix access violation exception on shutdown

src/runtime/Runtime.Delegates.cs, src/runtime/Runtime.cs
Was only used in the console and might not be available in some
embedding scenarios.
=> Drop reference to Py_Main

CHANGELOG.md, pythonnet.sln, shell.nix, src/runtime/ClassManager.cs, src/runtime/MethodBinder.cs, src/runtime/Types/ArrayObject.cs, src/runtime/Types/ClassBase.cs, src/runtime/Types/Indexer.cs, src/runtime/Util/ReflectionUtil.cs, tests/test_indexer.py
Implements `__delitem__` for `IList<T>` and `IDictionary<K,V>`
Fixes memory leak on using indexer setter.
Fixes crash on attempting to do `del o[...]` on .NET objects apart from arrays.
Fixes https://github.com/pythonnet/pythonnet/issues/2530
=> `__delitem__` for `IList<T>` and `IDictionary<K,V>`
