setup.py
=> Fix sdist and pip uninstall

src/runtime/assemblymanager.cs, src/runtime/moduleobject.cs
resolve issue https://github.com/pythonnet/pythonnet/issues/98 based from previous pull request
=> resolve https://github.com/pythonnet/pythonnet/issues/98

src/runtime/assemblymanager.cs
=> Fix for 3dsMax Python

src/runtime/converter.cs
=> Fix memory leak converting floats in converter.cs.

src/runtime/methodbinder.cs
=> Fix bug where the wrong overload is selected.

setup.py
Add Windows Kits 8.0 to 10.0 to setup.py so they can be used if installed
instead of the older Windows SDKs.
Also tidy up the Visual C++ for Python special case, to be used if
no other Windows SDKs/Kits are installed.
=> Build using installed Windows Kits, if any.

demo/wordpad.py, src/runtime/converter.cs, src/runtime/methodbinder.cs, src/tests/test_generic.py
…added tests for checking overloading behavior for main value types
=> fixes overloading of integer types which is py2/3 version dependent

.travis.yml, src/monoclr/pynetinit.c
Reverts pythonnet/pythonnet#181
This was done against master, but it should have been against develop.
=> Revert "Fix for #180"

src/runtime/classderived.cs, src/testing/subclasstest.cs, src/tests/test_subclass.py
and add simple example showing how to implement events.
=> Fix crash when abstract methods aren't implemented

src/runtime/methodbinder.cs, src/testing/methodtest.cs, src/tests/test_method.py
=> Fix and test for overload resolution when last parameter takes a non-"params" array

src/clrmodule/packages.config
https://github.com/pythonnet/pythonnet/issues/95
=> Update unmanaged exports

src/runtime/assemblymanager.cs
Old PR was still against develop.
=> Merge develop into master

src/runtime/importhook.cs
Cherry pick fix for #182 from PR #219
=> Cherry pick fix for #182 from PR #219

.travis.yml
Experiencing bug in travis build similar to
https://bugzilla.xamarin.com/show_bug.cgi?id=42058
=> Rollback to mono 4.2.4.4

src/runtime/classderived.cs, src/runtime/converter.cs, src/runtime/moduleobject.cs, src/runtime/pyobject.cs, src/runtime/pythonengine.cs, src/testing/Python.Test.csproj, src/testing/callbacktest.cs, src/tests/runtests.py, src/tests/test_suite/__init__.py, src/tests/test_suite/_missing_import.py, src/tests/test_suite/test_callback.py, src/tests/test_suite/test_import.py
Fixes a bunch issues I encountered when trying to implement https://github.com/matthid/googleMusicAllAccess.
Note: this includes #194 (because I needed the fix), let me know when you merge #194 so I can rebase and remove the last commit.
=> Some fixes.

src/runtime/classmanager.cs, src/testing/subclasstest.cs, src/tests/test_suite/__init__.py, src/tests/test_suite/test_recursiveTypes.py
Currently I added only the test, and I have no ETA when I can provide the fix. If anyone wants to step in, feel free. I noticed this with F# code (as the compiler will generate a lot of nested types when using DUs).
=> Fix a StackOverflowException.

setup.py
closes https://github.com/pythonnet/pythonnet/issues/288
=> Update setup.py to include geninterop.py in source distribution

.travis.yml, setup.py
https://github.com/pythonnet/pythonnet/issues/119
=> Work around a broken shared detection on some platforms

src/runtime/pyobject.cs
=> #296 Convert PyObject (cleanup)

setup.py, src/clrmodule/ClrModule.cs, src/clrmodule/clrmodule.csproj, src/runtime/Python.Runtime.csproj, src/runtime/converter.cs, src/runtime/delegateobject.cs, src/runtime/exceptions.cs, src/runtime/importhook.cs, src/runtime/interop.cs, src/runtime/pythonengine.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
Refactors all those pesky #if to simplify process of supporting newer python versions.
Theres a section in runtime I left untouched as it has many embbded directives.
=> Refactor directives

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
`issues`: Ensures that issues contain the basic necessary information
`pr`: Reminds author to add changes to changelog, authors, and add tests
=> Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

setup.py
https://github.com/pythonnet/pythonnet/issues/336
=> include fake c libs for pycparser to work

src/runtime/importhook.cs, src/runtime/interop.cs, src/runtime/pythonengine.cs
Fixes issue #262 by countering two memory corruption issues.
#262.
Is currently based on my other PR, but doesn't strictly need it, I could rebase.
=> Fix shutdown

src/runtime/importhook.cs
Refactor `importhook.cs` 
I wish...
=> Import hook clean-up

setup.py, src/runtime/Python.Runtime.csproj, src/runtime/x64/clrmodule-platform.il, src/runtime/x86/clrmodule-platform.il
Removes legacy arch specific `.il` files.
Doesn't seem to have any functionality.
=> Remove clrmodule_platform

CHANGELOG.md, ci/appveyor_run_tests.ps1, src/runtime/pyobject.cs
Fixes random crashes on AppVeyor Embedded tests.
Specifically, fixes crashes when exiting a program.
Closes #364
Closes #262
Maybe #245
Enables NUNIT's exit code to be part of the success criteria of the tests.
No new tests added since it affected all tests 👍 
=> Fix Pyobject GC Finalize & Enable NUnit Exit Code

src/embed_tests/pyimport.cs, src/tests/PyImportTest/sysargv.py, src/tests/runtests.py, src/tests/test_sysargv.py, src/tests/tests.pyproj
https://github.com/pythonnet/pythonnet/issues/299
=> Ensure that sys.argv is set

src/runtime/converter.cs, src/runtime/methodbinder.cs, src/runtime/methodbinding.cs
Refactor/Simplify converter & methondbind*.cs
`N/A`
Adds a note about needing to find the specific `Jython` section that `getprecedence` is based from. Maybe there's a better way to do it now?
=> Refactor converter.cs & methodbind*.cs

.editorconfig, src/tests/tests.pyproj
adds missing python scripts, adds search path (still need to add ..\..\build\..\ somehow)
No.
NA
-   [ ] Make sure to include one or more tests for your change - NA
-   [ ] If an enhancement PR, please create docs and at best an example - NA
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md) - NA
=> improve tests.pyproj for intellisense and running tests

CHANGELOG.md, src/embed_tests/pyinitialize.cs, src/runtime/runtime.cs
Fix Py_Main & PySys_SetArgvEx execution on PY3/UCS4 (Linux).
`N/A`
Based on @dmitriyse's work. 
https://github.com/dmitriyse/pythonnet/commit/8a70f09cb8faa9461d13480fb9ee2ee60b5b9acc
=> Fix Py_Main/PySys_SetArgvEx(...) UCS4/PY3 no mem

src/runtime/CustomMarshaler.cs, src/runtime/Python.Runtime.csproj, src/runtime/converter.cs, src/runtime/debughelper.cs, src/runtime/runtime.cs
Refactors conversions from Managed to Native type using `ICustomMarshaler`'s to handle the various conversions scenarios and manage releasing unmanaged memory.
#408 
This doesn't need to implement Native to Managed conversions as it's not needed for the purposes of the `pr`.
=> Refactor Managed-Native conversion - ICustomMarshaler

AUTHORS.md, CHANGELOG.md, conda.recipe/bld.bat, setup.py
https://github.com/pythonnet/pythonnet/issues/434
https://github.com/pythonnet/pythonnet/issues/434
https://github.com/pythonnet/pythonnet/issues/434
=> Msbuild15 patch

AUTHORS.md, CHANGELOG.md, src/runtime/moduleobject.cs, src/tests/test_module.py
Implements https://github.com/pythonnet/pythonnet/issues/432
Yes, #432 
...
=> Support clr.GetClrType() - as in IronPython

src/runtime/converter.cs, src/testing/conversiontest.cs, src/tests/test_conversion.py
=> Allow passing None for nullable args

AUTHORS.md, CHANGELOG.md
=> Updated CHANGELOG and AUTHORS

CHANGELOG.md, README.md
=> documentation update for keyword arguments

.travis.yml
https://github.com/pypa/setuptools/issues/1101
multiple pending pull requests
N/A
=> Update .travis.yml - setuptools breaking builds

setup.py
Fixes --xplat build when no mono available.
...
https://github.com/pythonnet/pythonnet/issues/571
...
...
=> Fixed problem with --xplat build when mono does not installed.

src/embed_tests/TestExample.cs
https://github.com/pythonnet/pythonnet/pull/596#issuecomment-364626728
Python 3.5 linux failures in CI
no
=> Temporary fix for failing tests with double vs single spaces

AUTHORS.md, CHANGELOG.md, src/runtime/converter.cs
=> Fixed errors breaking .NET Remoting on method invoke (#276)

AUTHORS.md, CHANGELOG.md, src/runtime/pyobject.cs
=> Fix PyObject.GetHashCode

CHANGELOG.md, src/runtime/iterator.cs, src/testing/exceptiontest.cs, src/tests/test_exceptions.py
This request contains the changes from #523 and adds some additional testing as requested in the comments on that request
Issue #475 
...
=> Catching exceptions from iterator MoveNext(), additional testing (issue #475, original pull request #523)

AUTHORS.md, CHANGELOG.md
This add links to issues and pull requests in the [`CHANGELOG`](../blob/master/CHANGELOG.md).
Closes #608.
...
=> Add links to issues and PRs in CHANGELOG

AUTHORS.md, CHANGELOG.md, requirements.txt, src/runtime/constructorbinding.cs, src/runtime/methodbinding.cs, src/runtime/overload.cs, src/testing/methodtest.cs, src/tests/test_method.py
Fix memory leaks due to spurious handle increment and add unit tests
...
Issue #691
...
...
-   [ x ] Make sure to include one or more tests for your change
-   [ x ] If an enhancement PR, please create docs and at best an example
-   [ x ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ x ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)
=> Fix memory leaks due to spurious handle increment and add unit tests

AUTHORS.md, CHANGELOG.md, src/runtime/assemblymanager.cs
As requested here: https://github.com/pythonnet/pythonnet/pull/538#issuecomment-364630052
Just a commnet
No. But comment was requested
=> Added inline comment about dangers of multidomain usage

src/runtime/runtime.cs
Adds more possible architecture names for x86 and amd64.
#772
=> Add a few more architecture names

CHANGELOG.md, src/runtime/exceptions.cs, src/tests/test_subclass.py
Attach traceback information to newly created exception.
#542
=> Add traceback information to exception

AUTHORS.md, CHANGELOG.md, src/runtime/methodbinder.cs
This is a refactoring/cleaning up of MethodBinder.Bind method. No new features were introduced.
This is a preliminary work necessary for #823.
The refactoring was mostly done using ReSharper with little manual interventions. The semantics should be preserved.
=> Refactoring of MethodBinder.Bind

src/runtime/finalizer.cs
- `finalizer` was leaking `_pendingArgs` (global memory) when the call
to `Py_AddPendingCall` was unsuccessful.
- Changing `lock` for `Monitor.TryEnter` at `AddPendingCollect()` so
threads don't block each other.
...
...
=> Fix memory leak in finalizer

README.rst
I've just added the shield to the README.
We should may also update
* https://github.com/pythonnet/pythonnet/wiki/Installation
* https://github.com/pythonnet/pythonnet.github.io
=> Mention conda-forge as installation option

src/runtime/runtime.cs, src/runtime/typemanager.cs
Adds ARM versions to the native page hack used to survive app-domain reloading.
#873
=> Support ARM architectures again

.travis.yml, src/runtime/Python.Runtime.15.csproj, src/runtime/Python.Runtime.csproj
This does not bring any new features, just enables use of C# 7.3 in Python.Runtime.
=> bump C# language version to 7.3 

AUTHORS.md, CHANGELOG.md, setup.py
I upgraded from `2.3.0` to `2.4.0` today, which seems to include [the addition of a `wheel` import in the `setup.py` file](https://github.com/pythonnet/pythonnet/blob/78d5d463dd41f54ce3c400e6288f418544c7ae81/setup.py#L18). I am trying to install my own package that includes `pythonnet` on a machine that does not typically have `wheel` installed, therefore, I have to include `wheel` in my `install_requires` file. The line looks like this, note that I have put `wheel` first to install it before `pythonnet`:
```
install_requires = ["wheel", "pythonnet==2.4.0"]  # pythonnet v2.4.0 requires wheel
```
Unfortunately, this still fails due to pip collecting all the packages first, which calls `python setup.py egg_info` for `pythonnet`, before `wheel` is installed (which occurs after all package …
=> Safe wheel import

.travis.yml
Pins Mono to 5.20 and simplifies the build.
Breaking build because of Mono 6.
Should help in running #925 .
=> Simplify travis config and pin mono to 5.20

src/runtime/typemanager.cs
Since I failed to provide properly working implementations of Return0 and Return1 for ARM, I'll just add the old behaviour back for all platforms but x86 and amd64.
#898
=> Readd .NET implementations of GC slots again

CHANGELOG.md, src/runtime/platform/Types.cs, src/runtime/runtime.cs
Adds support for the Jetson Nano
...
This closes #982 
...
...
Not sure how to test this, I don't have a Jetson Nano.
=> Adds support for the Jetson Nano

src/runtime/typemanager.cs
=> Remove unnecessary `CopySlot` calls(split from #958)

.editorconfig, src/runtime/extensiontype.cs, src/runtime/metatype.cs, src/runtime/pythonexception.cs, src/runtime/runtime.cs, src/runtime/typemanager.cs
Still has many refcnt error inside, since I use some new mechanisms for fixing other errors, if I fix them directly some tests may crash. So here just few fixes about the refcnt errors.
...
...
=> Fix refcnt errors (split from #958)

src/tests/test_repr.py
=> Fix simple typo: heirarchy -> hierarchy

src/runtime/importhook.cs, src/runtime/runtime.cs
* Add mechanism for calling XDecref and set member to null automately.
* Unified the GetBuiltins method
...
...
=> Decref the members of Runtime(split from #958)

src/embed_tests/TestPyObject.cs, src/runtime/pyint.cs, src/runtime/pyobject.cs
This adds basic validations to input parameters of various `PyObject` methods, which should help in debugging code, that uses Python.NET.
Also adds a few function overloads
No, but it reduces divergence with Lost Tech fork
=> Added parameter validation to PyObject methods

ci/appveyor_build_recipe.ps1, ci/appveyor_run_tests.ps1, src/perf_tests/PythonCallingNetBenchmark.cs
This is to diagnose #1050 [AppVeyor tests failing with timeout](https://github.com/pythonnet/pythonnet/issues/1050)
=> Report AppVeyor build timings

appveyor.yml
=> Disable 3.8 tests in AppVeyor, as they never pass yet anyway

AUTHORS.md, CHANGELOG.md, src/runtime/pyobject.cs, src/runtime/runtime.cs
IsNone() and GetPyNone() were needed for Numpy.NET to be able to find out if a PyObject is none. 
No.
These are in use for a long time now, I just now figured out how to PR them. I'll commit the necessary things from the checklist below.
=> Added IsNone() and GetPyNone()

CHANGELOG.md, setup.py, src/SharedAssemblyInfo.cs, src/clrmodule/ClrModule.cs, src/clrmodule/clrmodule.15.csproj, src/console/Console.15.csproj, src/embed_tests/Python.EmbeddingTest.15.csproj, src/runtime/Python.Runtime.15.csproj, src/runtime/resources/clr.py, src/testing/Python.Test.15.csproj
=> Prepare Release of 2.5.0

CHANGELOG.md, src/runtime/converter.cs
Remove remoting support
Removes some dependency on .NET framework
...
=> remove remoting block for .NET standard

appveyor.yml, src/embed_tests/TestConverter.cs, src/runtime/NewReference.cs, src/runtime/converter.cs, src/runtime/pyansistring.cs, src/runtime/pyfloat.cs, src/runtime/pyint.cs, src/runtime/pylong.cs, src/runtime/pyscope.cs, src/runtime/pystring.cs, src/runtime/pythonengine.cs, src/runtime/pythonexception.cs, src/runtime/pytuple.cs, src/tests/test_conversion.py
Fro saving unnecessary costs.
...
...
=> Remove unnecessary `CheckExceptionOccurred` calls

CHANGELOG.md, src/runtime/methodbinder.cs, src/testing/methodtest.cs, src/tests/test_method.py
Forward porting https://github.com/pythonnet/pythonnet/pull/1213 to `master`
=> Bad params object[] precedence (master)

src/perf_tests/Python.PerformanceTests.csproj, src/runtime/runtime.cs
=> really remove old versions

src/embed_tests/TestFinalizer.cs
Potential issue reported here: https://github.com/pythonnet/pythonnet/commit/610d309d62cecb1767c32a3d29df2ed06d13cde8#commitcomment-41601957
=> Added a test for finalization on shutdown

CHANGELOG.md, src/runtime/slots/mp_length.cs, src/runtime/typemanager.cs, src/tests/test_mp_length.py
=> Make `len` work for `ICollection<>` interface objects 

src/runtime/Codecs/DecoderGroup.cs, src/runtime/Codecs/EncoderGroup.cs, src/runtime/Codecs/RawProxyEncoder.cs, src/runtime/Codecs/TupleCodecs.cs, src/runtime/converterextensions.cs
=> Remove API warnings as these will be stabilised for 3.0

src/embed_tests/TestRuntime.cs, src/runtime/platform/LibraryLoader.cs, src/runtime/platform/NativeCodePage.cs, src/runtime/runtime.cs
Drops our own platform data code in favour of the .NET Standard API.
...
...
=> Replace custom platform handling by RuntimeInformation

.gitignore, pyproject.toml, requirements.txt, setup.py
Implements
- `python setup.py build_dotnet --inplace`
- `python setup.py develop`
- `pip install -e .`
This allows for easier development, it should now be enough to run on of
these for changes to the .NET code.
Helps with #1316.
...
=> Implement inplace building and develop

src/runtime/BorrowedReference.cs, src/runtime/assemblymanager.cs, src/runtime/classobject.cs, src/runtime/finalizer.cs, src/runtime/genericutil.cs, src/runtime/interop.cs, src/testing/eventtest.cs
=> Fix or disable warnings in Python.Runtime

src/runtime/arrayobject.cs, src/tests/test_array.py
A float value as an array index will raise an error.  Fixes an oversight in #1343
The comment in #1342 
...
=> Disable implicit conversion from float to array index

CHANGELOG.md, src/embed_tests/TestPythonException.cs, src/runtime/pythonexception.cs
Fixes #1359 by joining the traceback lines and separates the .NET stacktrace by an additional line.
#1359 
...
=> Fix exception string

.github/workflows/nuget-preview.yml, Directory.Build.props, LICENSE, pythonnet.sln, src/runtime/Python.Runtime.csproj
This generates monthly release previews on NuGet using GitHub actions
#1379
=> Monthly NuGet release previews

src/embed_tests/TestInterrupt.cs
Should resolve this failure: https://github.com/pythonnet/pythonnet/pull/1392/checks?check_run_id=1944113649
Related to https://github.com/pythonnet/pythonnet/pull/1337
This adds proper synchronization to thread shared variables in the test, and sets explicit timeouts.
=> Made InterruptTest more robust

src/embed_tests/GlobalTestsSetup.cs, src/embed_tests/TestFinalizer.cs, src/embed_tests/TestNativeTypeOffset.cs, src/embed_tests/TestPythonException.cs, src/embed_tests/TestRuntime.cs, src/embed_tests/pyimport.cs, src/embed_tests/pyinitialize.cs, src/runtime/BorrowedReference.cs, src/runtime/CustomMarshaler.cs, src/runtime/exceptions.cs, src/runtime/importhook.cs, src/runtime/pymodule.cs, src/runtime/pyscope.cs, src/runtime/pystring.cs, src/runtime/pythonengine.cs, src/runtime/pythonexception.cs, src/runtime/runtime.cs, src/runtime/runtime_state.cs, src/runtime/tricks/NullOnly.cs, src/testing/threadtest.cs
Also allow `BorrowedReference == null` comparison.
=> Remove Utf8Marshaler, set PyScope base class to PyObject, added PyModule

src/runtime/converter.cs
port of 8e1d4dbf7b0e647482b302bf2ce7ad36f0b9d0f5
Prevents crash on converting sequences to arrays when sequence lacks `__len__`.
Sequence types might return error from `PySequence_Size` (like sequences provided by generators or types implemented in C, that lack `sq_length` slot or make it throw). This change adds handling for this case.
=> Fixed crash in ToArray when sequence explicitly denies __len__

src/runtime/metatype.cs
It should have not been allowed in the first place, but we accidentally cleared `Ready` from `tp_flags`. Instead, we will extend `tp_flags` and call `PyType_Modified` at the end of CLR MetaType.tp_new
No
This change is required for the upcoming feature, that allows setting custom base type for reflected .NET classes (as seen from Python).
=> Fixed double call to `PyType_Ready` in CLR MetaType's `tp_new`

src/embed_tests/Codecs.cs, src/runtime/converter.cs
Custom codecs were ignored for `DateTime` and `Decimal` because they have special values in `TypeCode`, which was not accounted for.
#1496
Needs to be backported to 2.5
@innominate227 if you can review, this might get in faster.
=> Fixed custom decoders not working for DateTime and Decimal

src/runtime/typemanager.cs
=> Validate, that custom Python base types can be inherited from

CHANGELOG.md
Updates the changelog on the `backports-2.5` branch with the latest release.
-   [x] <s>Make sure to include one or more tests for your change</s>
-   [x] <s>If an enhancement PR, please create docs and at best an example</s>
-   [x] <s>Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)</s> not significant
-   [x] Updated the CHANGELOG
=> Update headline of backports changelog to latest release

CHANGELOG.md, src/runtime/InteropConfiguration.cs, src/runtime/Mixins/CollectionMixinsProvider.cs, src/runtime/Mixins/collections.py, src/runtime/Python.Runtime.csproj, src/runtime/Util.cs, src/runtime/classbase.cs, src/runtime/clrobject.cs, src/runtime/managedtype.cs, src/runtime/pyscope.cs, src/runtime/pythonengine.cs, src/runtime/pytype.cs, src/runtime/runtime.cs, tests/test_collection_mixins.py
This enables Python users to handle .NET collections in pythonic way.
N/A
...
=> Mixins for standard collections that implement `collections.abc` interfaces

src/embed_tests/Inheritance.cs
closes https://github.com/pythonnet/pythonnet/issues/1420
=> Added a regression test for calling base method from nested class

.github/workflows/ARM.yml, .github/workflows/main.yml
=> Only run CI on pushes to master and on all pull requests

.github/PULL_REQUEST_TEMPLATE.md
Added a not to PR Github template to remind contributors to sign CLA
N/A
N/A
-   Make sure to include one or more tests for your change: ⚠️ N/A
-   If an enhancement PR, please create docs and at best an example: ⚠️ N/A
=> Added todo note to ensure CLA is signed

src/runtime/PythonEngine.cs
=> We can drop the import hack as we are now using the newer import mechanics

.github/workflows/main.yml, src/runtime/Native/NativeTypeSpec.cs, tests/conftest.py
=> Fix layout of `NativeTypeSpec` on 32 bit platforms

CHANGELOG.md, src/runtime/MethodBinder.cs, src/testing/Python.Test.csproj, src/testing/methodtest.cs, tests/test_method.py
- Add test for Decimal default parameter
- Drop outdated work around to fix decimal default parameters
Fixes #1769
=> Fix decimal default parameters

CHANGELOG.md, src/runtime/PythonEngine.cs, tests/test_codec.py, tests/test_conversion.py, tests/test_engine.py
Fixes #1724, supersedes #1798.
...
...
=> `Min`/`MaxSupportedVersion` and `IsSupportedVersion` on `PythonEngine`

src/embed_tests/NumPyTests.cs
Adds tests for #1804.
Nope.
...
=> Add explicit tests for vararg call

demo/helloform.py, demo/splitter.py, demo/wordpad.py
Fixes the demo scripts (@burque505, FYI)
...
@lostmsu Do you remember when the behaviour of the constructor changed? Apparently, we now require an explicit call to `__init__` for a class that derives from a .NET class, it seems like this used to be handled in `__new__`.
=> Fix demo scripts

src/runtime/Types/MethodObject.cs
=> fixed ForbidPythonThreadsAttribute being ignored in certain scenarios

tests/test_enum.py
=> Add test for enum int conversion

src/runtime/PythonEngine.cs
#1831
#1831 #1832 
Supercedes #1832.
=> Take GIL when checking if error occurred on shutdown

src/runtime/AssemblyManager.cs, src/runtime/Python.Runtime.csproj, src/runtime/Runtime.cs, src/runtime/Types/ArrayObject.cs, src/runtime/Types/EventBinding.cs, src/runtime/Types/ReflectedClrType.cs
also fixed issues with xml docs in the code
implements https://github.com/pythonnet/pythonnet/issues/1876
=> Add XML docs to NuGet

src/embed_tests/Codecs.cs
Fixes https://github.com/pythonnet/pythonnet/issues/1256
=> Enabled test for NoStackOverflowOnSystemType

src/runtime/Types/ClassDerived.cs, src/testing/interfacetest.cs, tests/test_subclass.py
=> Fix implementing a generic interface with a Python class

CHANGELOG.md, pythonnet/__init__.py
Fixes an oversight in that `_LOADED` was never set in `pythonnet.load`.
#2078 
...
=> Ensure that `load` only runs once

doc/source/dotnet.rst
=> Remove suggestions to use `internal` functions

src/embed_tests/Modules.cs, src/runtime/PythonTypes/PyModule.cs
…al package structure
So virtual package structures can be created.
Issue 2043
Change piggy backs off of existing static method.
=> Allow setting of the python module file

.github/workflows/main.yml, AUTHORS.md, CHANGELOG.md
Fixes the CI/CD job to properly exclude the intended job
No
No
=> ci: properly exclude job
